//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPacBusiness.CuentasAcreedorWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softpacws.pucp.edu.pe/", ConfigurationName="CuentasAcreedorWS.CuentasAcreedorWS")]
    public interface CuentasAcreedorWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/obtenerCuentasPorAcreedor_v2Reques" +
            "t", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/obtenerCuentasPorAcreedor_v2Respon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Response obtenerCuentasPorAcreedor_v2(SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/obtenerCuentasPorAcreedor_v2Reques" +
            "t", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/obtenerCuentasPorAcreedor_v2Respon" +
            "se")]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Response> obtenerCuentasPorAcreedor_v2Async(SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Request request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/eliminarCuentaAcreedorParametrosRe" +
            "quest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/eliminarCuentaAcreedorParametrosRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosResponse eliminarCuentaAcreedorParametros(SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/eliminarCuentaAcreedorParametrosRe" +
            "quest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/eliminarCuentaAcreedorParametrosRe" +
            "sponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosResponse> eliminarCuentaAcreedorParametrosAsync(SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/listarCuentasAcreedorRequest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/listarCuentasAcreedorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorResponse listarCuentasAcreedor(SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/listarCuentasAcreedorRequest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/listarCuentasAcreedorResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorResponse> listarCuentasAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/obtenerCuentasPorAcreedorRequest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/obtenerCuentasPorAcreedorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorResponse obtenerCuentasPorAcreedor(SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/obtenerCuentasPorAcreedorRequest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/obtenerCuentasPorAcreedorResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorResponse> obtenerCuentasPorAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/obtenerCuentaAcreedorRequest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/obtenerCuentaAcreedorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorResponse obtenerCuentaAcreedor(SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/obtenerCuentaAcreedorRequest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/obtenerCuentaAcreedorResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorResponse> obtenerCuentaAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/modificarCuentasAcreedorRequest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/modificarCuentasAcreedorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorResponse modificarCuentasAcreedor(SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/modificarCuentasAcreedorRequest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/modificarCuentasAcreedorResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorResponse> modificarCuentasAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/insertarCuentasAcreedorRequest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/insertarCuentasAcreedorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorResponse insertarCuentasAcreedor(SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/insertarCuentasAcreedorRequest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/insertarCuentasAcreedorResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorResponse> insertarCuentasAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/eliminarCuentaAcreedorRequest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/eliminarCuentaAcreedorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorResponse eliminarCuentaAcreedor(SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/eliminarCuentaAcreedorRequest", ReplyAction="http://softpacws.pucp.edu.pe/CuentasAcreedorWS/eliminarCuentaAcreedorResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorResponse> eliminarCuentaAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class cuentasAcreedorDTO : cuentasBancariasDTO {
        
        private acreedoresDTO acreedorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public acreedoresDTO acreedor {
            get {
                return this.acreedorField;
            }
            set {
                this.acreedorField = value;
                this.RaisePropertyChanged("acreedor");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class acreedoresDTO : eliminableDTOBase {
        
        private int acreedor_idField;
        
        private bool acreedor_idFieldSpecified;
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string condicionField;
        
        private string direccion_fiscalField;
        
        private paisesDTO paisField;
        
        private int plazo_de_pagoField;
        
        private bool plazo_de_pagoFieldSpecified;
        
        private string razon_socialField;
        
        private string rucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int acreedor_id {
            get {
                return this.acreedor_idField;
            }
            set {
                this.acreedor_idField = value;
                this.RaisePropertyChanged("acreedor_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acreedor_idSpecified {
            get {
                return this.acreedor_idFieldSpecified;
            }
            set {
                this.acreedor_idFieldSpecified = value;
                this.RaisePropertyChanged("acreedor_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string condicion {
            get {
                return this.condicionField;
            }
            set {
                this.condicionField = value;
                this.RaisePropertyChanged("condicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccion_fiscal {
            get {
                return this.direccion_fiscalField;
            }
            set {
                this.direccion_fiscalField = value;
                this.RaisePropertyChanged("direccion_fiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public paisesDTO pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int plazo_de_pago {
            get {
                return this.plazo_de_pagoField;
            }
            set {
                this.plazo_de_pagoField = value;
                this.RaisePropertyChanged("plazo_de_pago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plazo_de_pagoSpecified {
            get {
                return this.plazo_de_pagoFieldSpecified;
            }
            set {
                this.plazo_de_pagoFieldSpecified = value;
                this.RaisePropertyChanged("plazo_de_pagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string razon_social {
            get {
                return this.razon_socialField;
            }
            set {
                this.razon_socialField = value;
                this.RaisePropertyChanged("razon_social");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class paisesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_isoField;
        
        private string codigo_telefonicoField;
        
        private string nombreField;
        
        private int pais_idField;
        
        private bool pais_idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo_iso {
            get {
                return this.codigo_isoField;
            }
            set {
                this.codigo_isoField = value;
                this.RaisePropertyChanged("codigo_iso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo_telefonico {
            get {
                return this.codigo_telefonicoField;
            }
            set {
                this.codigo_telefonicoField = value;
                this.RaisePropertyChanged("codigo_telefonico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int pais_id {
            get {
                return this.pais_idField;
            }
            set {
                this.pais_idField = value;
                this.RaisePropertyChanged("pais_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pais_idSpecified {
            get {
                return this.pais_idFieldSpecified;
            }
            set {
                this.pais_idFieldSpecified = value;
                this.RaisePropertyChanged("pais_idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class tiposDeCambioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private monedasDTO moneda_destinoField;
        
        private monedasDTO moneda_origenField;
        
        private decimal tasa_de_cambioField;
        
        private bool tasa_de_cambioFieldSpecified;
        
        private int tipo_cambio_idField;
        
        private bool tipo_cambio_idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public monedasDTO moneda_destino {
            get {
                return this.moneda_destinoField;
            }
            set {
                this.moneda_destinoField = value;
                this.RaisePropertyChanged("moneda_destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public monedasDTO moneda_origen {
            get {
                return this.moneda_origenField;
            }
            set {
                this.moneda_origenField = value;
                this.RaisePropertyChanged("moneda_origen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal tasa_de_cambio {
            get {
                return this.tasa_de_cambioField;
            }
            set {
                this.tasa_de_cambioField = value;
                this.RaisePropertyChanged("tasa_de_cambio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tasa_de_cambioSpecified {
            get {
                return this.tasa_de_cambioFieldSpecified;
            }
            set {
                this.tasa_de_cambioFieldSpecified = value;
                this.RaisePropertyChanged("tasa_de_cambioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int tipo_cambio_id {
            get {
                return this.tipo_cambio_idField;
            }
            set {
                this.tipo_cambio_idField = value;
                this.RaisePropertyChanged("tipo_cambio_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipo_cambio_idSpecified {
            get {
                return this.tipo_cambio_idFieldSpecified;
            }
            set {
                this.tipo_cambio_idFieldSpecified = value;
                this.RaisePropertyChanged("tipo_cambio_idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class monedasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_isoField;
        
        private int moneda_idField;
        
        private bool moneda_idFieldSpecified;
        
        private string nombreField;
        
        private string simboloField;
        
        private tiposDeCambioDTO[] tipos_cambioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo_iso {
            get {
                return this.codigo_isoField;
            }
            set {
                this.codigo_isoField = value;
                this.RaisePropertyChanged("codigo_iso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int moneda_id {
            get {
                return this.moneda_idField;
            }
            set {
                this.moneda_idField = value;
                this.RaisePropertyChanged("moneda_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moneda_idSpecified {
            get {
                return this.moneda_idFieldSpecified;
            }
            set {
                this.moneda_idFieldSpecified = value;
                this.RaisePropertyChanged("moneda_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string simbolo {
            get {
                return this.simboloField;
            }
            set {
                this.simboloField = value;
                this.RaisePropertyChanged("simbolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipos_cambio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public tiposDeCambioDTO[] tipos_cambio {
            get {
                return this.tipos_cambioField;
            }
            set {
                this.tipos_cambioField = value;
                this.RaisePropertyChanged("tipos_cambio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class entidadesBancariasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_swiftField;
        
        private int entidad_bancaria_idField;
        
        private bool entidad_bancaria_idFieldSpecified;
        
        private string formato_aceptadoField;
        
        private string nombreField;
        
        private paisesDTO paisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo_swift {
            get {
                return this.codigo_swiftField;
            }
            set {
                this.codigo_swiftField = value;
                this.RaisePropertyChanged("codigo_swift");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int entidad_bancaria_id {
            get {
                return this.entidad_bancaria_idField;
            }
            set {
                this.entidad_bancaria_idField = value;
                this.RaisePropertyChanged("entidad_bancaria_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entidad_bancaria_idSpecified {
            get {
                return this.entidad_bancaria_idFieldSpecified;
            }
            set {
                this.entidad_bancaria_idFieldSpecified = value;
                this.RaisePropertyChanged("entidad_bancaria_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string formato_aceptado {
            get {
                return this.formato_aceptadoField;
            }
            set {
                this.formato_aceptadoField = value;
                this.RaisePropertyChanged("formato_aceptado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public paisesDTO pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class usuarioPaisAccesoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool accesoField;
        
        private bool accesoFieldSpecified;
        
        private paisesDTO paisField;
        
        private usuariosDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool acceso {
            get {
                return this.accesoField;
            }
            set {
                this.accesoField = value;
                this.RaisePropertyChanged("acceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accesoSpecified {
            get {
                return this.accesoFieldSpecified;
            }
            set {
                this.accesoFieldSpecified = value;
                this.RaisePropertyChanged("accesoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public paisesDTO pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public usuariosDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class usuariosDTO : eliminableDTOBase {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string apellidosField;
        
        private string correo_electronicoField;
        
        private string nombreField;
        
        private string nombre_de_usuarioField;
        
        private string password_hashField;
        
        private bool superusuarioField;
        
        private bool superusuarioFieldSpecified;
        
        private int usuario_idField;
        
        private bool usuario_idFieldSpecified;
        
        private usuarioPaisAccesoDTO[] usuario_paisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo_electronico {
            get {
                return this.correo_electronicoField;
            }
            set {
                this.correo_electronicoField = value;
                this.RaisePropertyChanged("correo_electronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre_de_usuario {
            get {
                return this.nombre_de_usuarioField;
            }
            set {
                this.nombre_de_usuarioField = value;
                this.RaisePropertyChanged("nombre_de_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string password_hash {
            get {
                return this.password_hashField;
            }
            set {
                this.password_hashField = value;
                this.RaisePropertyChanged("password_hash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool superusuario {
            get {
                return this.superusuarioField;
            }
            set {
                this.superusuarioField = value;
                this.RaisePropertyChanged("superusuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool superusuarioSpecified {
            get {
                return this.superusuarioFieldSpecified;
            }
            set {
                this.superusuarioFieldSpecified = value;
                this.RaisePropertyChanged("superusuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int usuario_id {
            get {
                return this.usuario_idField;
            }
            set {
                this.usuario_idField = value;
                this.RaisePropertyChanged("usuario_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuario_idSpecified {
            get {
                return this.usuario_idFieldSpecified;
            }
            set {
                this.usuario_idFieldSpecified = value;
                this.RaisePropertyChanged("usuario_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("usuario_pais", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public usuarioPaisAccesoDTO[] usuario_pais {
            get {
                return this.usuario_paisField;
            }
            set {
                this.usuario_paisField = value;
                this.RaisePropertyChanged("usuario_pais");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(acreedoresDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cuentasBancariasDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cuentasAcreedorDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuariosDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public abstract partial class eliminableDTOBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fecha_eliminacionField;
        
        private bool fecha_eliminacionFieldSpecified;
        
        private usuariosDTO usuario_eliminacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha_eliminacion {
            get {
                return this.fecha_eliminacionField;
            }
            set {
                this.fecha_eliminacionField = value;
                this.RaisePropertyChanged("fecha_eliminacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_eliminacionSpecified {
            get {
                return this.fecha_eliminacionFieldSpecified;
            }
            set {
                this.fecha_eliminacionFieldSpecified = value;
                this.RaisePropertyChanged("fecha_eliminacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public usuariosDTO usuario_eliminacion {
            get {
                return this.usuario_eliminacionField;
            }
            set {
                this.usuario_eliminacionField = value;
                this.RaisePropertyChanged("usuario_eliminacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cuentasAcreedorDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public abstract partial class cuentasBancariasDTO : eliminableDTOBase {
        
        private bool activaField;
        
        private bool activaFieldSpecified;
        
        private string cciField;
        
        private int cuenta_bancaria_idField;
        
        private bool cuenta_bancaria_idFieldSpecified;
        
        private entidadesBancariasDTO entidad_bancariaField;
        
        private monedasDTO monedaField;
        
        private string numero_cuentaField;
        
        private string tipo_cuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activaSpecified {
            get {
                return this.activaFieldSpecified;
            }
            set {
                this.activaFieldSpecified = value;
                this.RaisePropertyChanged("activaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cci {
            get {
                return this.cciField;
            }
            set {
                this.cciField = value;
                this.RaisePropertyChanged("cci");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int cuenta_bancaria_id {
            get {
                return this.cuenta_bancaria_idField;
            }
            set {
                this.cuenta_bancaria_idField = value;
                this.RaisePropertyChanged("cuenta_bancaria_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cuenta_bancaria_idSpecified {
            get {
                return this.cuenta_bancaria_idFieldSpecified;
            }
            set {
                this.cuenta_bancaria_idFieldSpecified = value;
                this.RaisePropertyChanged("cuenta_bancaria_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public entidadesBancariasDTO entidad_bancaria {
            get {
                return this.entidad_bancariaField;
            }
            set {
                this.entidad_bancariaField = value;
                this.RaisePropertyChanged("entidad_bancaria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public monedasDTO moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string numero_cuenta {
            get {
                return this.numero_cuentaField;
            }
            set {
                this.numero_cuentaField = value;
                this.RaisePropertyChanged("numero_cuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipo_cuenta {
            get {
                return this.tipo_cuentaField;
            }
            set {
                this.tipo_cuentaField = value;
                this.RaisePropertyChanged("tipo_cuenta");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCuentasPorAcreedor_v2", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCuentasPorAcreedor_v2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int acreedor_id;
        
        public obtenerCuentasPorAcreedor_v2Request() {
        }
        
        public obtenerCuentasPorAcreedor_v2Request(int acreedor_id) {
            this.acreedor_id = acreedor_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCuentasPorAcreedor_v2Response", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCuentasPorAcreedor_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO[] @return;
        
        public obtenerCuentasPorAcreedor_v2Response() {
        }
        
        public obtenerCuentasPorAcreedor_v2Response(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCuentaAcreedorParametros", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCuentaAcreedorParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.CuentasAcreedorWS.usuariosDTO usuarioActual;
        
        public eliminarCuentaAcreedorParametrosRequest() {
        }
        
        public eliminarCuentaAcreedorParametrosRequest(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta, SoftPacBusiness.CuentasAcreedorWS.usuariosDTO usuarioActual) {
            this.cuenta = cuenta;
            this.usuarioActual = usuarioActual;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCuentaAcreedorParametrosResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCuentaAcreedorParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCuentaAcreedorParametrosResponse() {
        }
        
        public eliminarCuentaAcreedorParametrosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCuentasAcreedor", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCuentasAcreedorRequest {
        
        public listarCuentasAcreedorRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCuentasAcreedorResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCuentasAcreedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO[] @return;
        
        public listarCuentasAcreedorResponse() {
        }
        
        public listarCuentasAcreedorResponse(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCuentasPorAcreedor", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCuentasPorAcreedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int acreedor_id;
        
        public obtenerCuentasPorAcreedorRequest() {
        }
        
        public obtenerCuentasPorAcreedorRequest(int acreedor_id) {
            this.acreedor_id = acreedor_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCuentasPorAcreedorResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCuentasPorAcreedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO[] @return;
        
        public obtenerCuentasPorAcreedorResponse() {
        }
        
        public obtenerCuentasPorAcreedorResponse(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCuentaAcreedor", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCuentaAcreedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cuenta_acreedor_id;
        
        public obtenerCuentaAcreedorRequest() {
        }
        
        public obtenerCuentaAcreedorRequest(int cuenta_acreedor_id) {
            this.cuenta_acreedor_id = cuenta_acreedor_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCuentaAcreedorResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCuentaAcreedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO @return;
        
        public obtenerCuentaAcreedorResponse() {
        }
        
        public obtenerCuentaAcreedorResponse(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCuentasAcreedor", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCuentasAcreedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta;
        
        public modificarCuentasAcreedorRequest() {
        }
        
        public modificarCuentasAcreedorRequest(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta) {
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCuentasAcreedorResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCuentasAcreedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCuentasAcreedorResponse() {
        }
        
        public modificarCuentasAcreedorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCuentasAcreedor", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCuentasAcreedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta;
        
        public insertarCuentasAcreedorRequest() {
        }
        
        public insertarCuentasAcreedorRequest(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta) {
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCuentasAcreedorResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCuentasAcreedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCuentasAcreedorResponse() {
        }
        
        public insertarCuentasAcreedorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCuentaAcreedor", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCuentaAcreedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta_acreedor;
        
        public eliminarCuentaAcreedorRequest() {
        }
        
        public eliminarCuentaAcreedorRequest(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta_acreedor) {
            this.cuenta_acreedor = cuenta_acreedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCuentaAcreedorResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCuentaAcreedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCuentaAcreedorResponse() {
        }
        
        public eliminarCuentaAcreedorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CuentasAcreedorWSChannel : SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuentasAcreedorWSClient : System.ServiceModel.ClientBase<SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS>, SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS {
        
        public CuentasAcreedorWSClient() {
        }
        
        public CuentasAcreedorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuentasAcreedorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentasAcreedorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentasAcreedorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Response SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2(SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Request request) {
            return base.Channel.obtenerCuentasPorAcreedor_v2(request);
        }
        
        public SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO[] obtenerCuentasPorAcreedor_v2(int acreedor_id) {
            SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Request inValue = new SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Request();
            inValue.acreedor_id = acreedor_id;
            SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Response retVal = ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).obtenerCuentasPorAcreedor_v2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Response> SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Async(SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Request request) {
            return base.Channel.obtenerCuentasPorAcreedor_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Response> obtenerCuentasPorAcreedor_v2Async(int acreedor_id) {
            SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Request inValue = new SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedor_v2Request();
            inValue.acreedor_id = acreedor_id;
            return ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).obtenerCuentasPorAcreedor_v2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosResponse SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.eliminarCuentaAcreedorParametros(SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosRequest request) {
            return base.Channel.eliminarCuentaAcreedorParametros(request);
        }
        
        public int eliminarCuentaAcreedorParametros(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta, SoftPacBusiness.CuentasAcreedorWS.usuariosDTO usuarioActual) {
            SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosRequest();
            inValue.cuenta = cuenta;
            inValue.usuarioActual = usuarioActual;
            SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosResponse retVal = ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).eliminarCuentaAcreedorParametros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosResponse> SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosAsync(SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosRequest request) {
            return base.Channel.eliminarCuentaAcreedorParametrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosResponse> eliminarCuentaAcreedorParametrosAsync(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta, SoftPacBusiness.CuentasAcreedorWS.usuariosDTO usuarioActual) {
            SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorParametrosRequest();
            inValue.cuenta = cuenta;
            inValue.usuarioActual = usuarioActual;
            return ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).eliminarCuentaAcreedorParametrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorResponse SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.listarCuentasAcreedor(SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorRequest request) {
            return base.Channel.listarCuentasAcreedor(request);
        }
        
        public SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO[] listarCuentasAcreedor() {
            SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorRequest();
            SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorResponse retVal = ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).listarCuentasAcreedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorResponse> SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.listarCuentasAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorRequest request) {
            return base.Channel.listarCuentasAcreedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorResponse> listarCuentasAcreedorAsync() {
            SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.listarCuentasAcreedorRequest();
            return ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).listarCuentasAcreedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorResponse SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.obtenerCuentasPorAcreedor(SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorRequest request) {
            return base.Channel.obtenerCuentasPorAcreedor(request);
        }
        
        public SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO[] obtenerCuentasPorAcreedor(int acreedor_id) {
            SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorRequest();
            inValue.acreedor_id = acreedor_id;
            SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorResponse retVal = ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).obtenerCuentasPorAcreedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorResponse> SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.obtenerCuentasPorAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorRequest request) {
            return base.Channel.obtenerCuentasPorAcreedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorResponse> obtenerCuentasPorAcreedorAsync(int acreedor_id) {
            SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.obtenerCuentasPorAcreedorRequest();
            inValue.acreedor_id = acreedor_id;
            return ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).obtenerCuentasPorAcreedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorResponse SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.obtenerCuentaAcreedor(SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorRequest request) {
            return base.Channel.obtenerCuentaAcreedor(request);
        }
        
        public SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO obtenerCuentaAcreedor(int cuenta_acreedor_id) {
            SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorRequest();
            inValue.cuenta_acreedor_id = cuenta_acreedor_id;
            SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorResponse retVal = ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).obtenerCuentaAcreedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorResponse> SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.obtenerCuentaAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorRequest request) {
            return base.Channel.obtenerCuentaAcreedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorResponse> obtenerCuentaAcreedorAsync(int cuenta_acreedor_id) {
            SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.obtenerCuentaAcreedorRequest();
            inValue.cuenta_acreedor_id = cuenta_acreedor_id;
            return ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).obtenerCuentaAcreedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorResponse SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.modificarCuentasAcreedor(SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorRequest request) {
            return base.Channel.modificarCuentasAcreedor(request);
        }
        
        public int modificarCuentasAcreedor(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta) {
            SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorRequest();
            inValue.cuenta = cuenta;
            SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorResponse retVal = ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).modificarCuentasAcreedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorResponse> SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.modificarCuentasAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorRequest request) {
            return base.Channel.modificarCuentasAcreedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorResponse> modificarCuentasAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta) {
            SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.modificarCuentasAcreedorRequest();
            inValue.cuenta = cuenta;
            return ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).modificarCuentasAcreedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorResponse SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.insertarCuentasAcreedor(SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorRequest request) {
            return base.Channel.insertarCuentasAcreedor(request);
        }
        
        public int insertarCuentasAcreedor(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta) {
            SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorRequest();
            inValue.cuenta = cuenta;
            SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorResponse retVal = ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).insertarCuentasAcreedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorResponse> SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.insertarCuentasAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorRequest request) {
            return base.Channel.insertarCuentasAcreedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorResponse> insertarCuentasAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta) {
            SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.insertarCuentasAcreedorRequest();
            inValue.cuenta = cuenta;
            return ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).insertarCuentasAcreedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorResponse SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.eliminarCuentaAcreedor(SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorRequest request) {
            return base.Channel.eliminarCuentaAcreedor(request);
        }
        
        public int eliminarCuentaAcreedor(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta_acreedor) {
            SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorRequest();
            inValue.cuenta_acreedor = cuenta_acreedor;
            SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorResponse retVal = ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).eliminarCuentaAcreedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorResponse> SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS.eliminarCuentaAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorRequest request) {
            return base.Channel.eliminarCuentaAcreedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorResponse> eliminarCuentaAcreedorAsync(SoftPacBusiness.CuentasAcreedorWS.cuentasAcreedorDTO cuenta_acreedor) {
            SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorRequest inValue = new SoftPacBusiness.CuentasAcreedorWS.eliminarCuentaAcreedorRequest();
            inValue.cuenta_acreedor = cuenta_acreedor;
            return ((SoftPacBusiness.CuentasAcreedorWS.CuentasAcreedorWS)(this)).eliminarCuentaAcreedorAsync(inValue);
        }
    }
}
