-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema softpacbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema softpacbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `softpacbd` DEFAULT CHARACTER SET utf8 ;
USE `softpacbd` ;

-- -----------------------------------------------------
-- Table `softpacbd`.`PA_USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_USUARIOS` (
  `USUARIO_ID` INT NOT NULL,
  `CORREO_ELECTRONICO` VARCHAR(45) NOT NULL,
  `NOMBRE_DE_USUARIO` VARCHAR(45) NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `APELLIDOS` VARCHAR(45) NULL,
  `ACTIVO` CHAR(1) NOT NULL,
  `PASSWORD_HASH` VARCHAR(45) NOT NULL,
  `SUPERUSUARIO` CHAR(1) NOT NULL DEFAULT 'N',
  `FECHA_ELIMINACION` DATETIME NULL,
  `USUARIO_ELIMINACION` INT NULL,
  PRIMARY KEY (`USUARIO_ID`),
  INDEX `fk_PA_USUARIOS_PA_USUARIOS1_idx` (`USUARIO_ELIMINACION` ASC) VISIBLE,
  CONSTRAINT `fk_PA_USUARIOS_PA_USUARIOS`
    FOREIGN KEY (`USUARIO_ELIMINACION`)
    REFERENCES `softpacbd`.`PA_USUARIOS` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_PAISES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_PAISES` (
  `PAIS_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(60) NOT NULL,
  `CODIGO_ISO` CHAR(2) NOT NULL,
  `CODIGO_TELEFONICO` CHAR(3) NULL,
  PRIMARY KEY (`PAIS_ID`),
  UNIQUE INDEX `UQ_PA_PAISES_NOMBRE` (`NOMBRE` ASC) VISIBLE,
  UNIQUE INDEX `UQ_PA_PAISES_CODIGO_ISO` (`CODIGO_ISO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_USUARIO_PAIS_ACCESO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_USUARIO_PAIS_ACCESO` (
  `USUARIO_ID` INT NOT NULL,
  `ACCESO` CHAR(1) NOT NULL,
  `PAIS_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`USUARIO_ID`),
  INDEX `fk_PA_USUARIO_PAIS_ACCESO_PA_PAISES1_idx` (`PAIS_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PA_USUARIO_PAIS_ACCESO_PA_USUARIOS1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `softpacbd`.`PA_USUARIOS` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_USUARIO_PAIS_ACCESO_PA_PAISES`
    FOREIGN KEY (`PAIS_ID`)
    REFERENCES `softpacbd`.`PA_PAISES` (`PAIS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_ACREEDORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_ACREEDORES` (
  `ACREEDOR_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RAZON_SOCIAL` VARCHAR(200) NOT NULL,
  `RUC` CHAR(11) NOT NULL,
  `DIRECCION_FISCAL` VARCHAR(200) NOT NULL,
  `CONDICION` VARCHAR(100) NULL,
  `PLAZO_DE_PAGO` INT NOT NULL,
  `ACTIVO` CHAR(1) NOT NULL DEFAULT 'S',
  `PAIS_ID` INT UNSIGNED NOT NULL,
  `FECHA_ELIMINACION` DATETIME NULL,
  `USUARIO_ELIMINACION` INT NULL,
  PRIMARY KEY (`ACREEDOR_ID`),
  UNIQUE INDEX `UQ_PA_ACREEDORES_RUC` (`RUC` ASC) VISIBLE,
  INDEX `IDX_PA_ACREEDORES_PAIS_ID` (`PAIS_ID` ASC) VISIBLE,
  INDEX `fk_PA_ACREEDORES_PA_USUARIOS1_idx` (`USUARIO_ELIMINACION` ASC) VISIBLE,
  CONSTRAINT `FK_PA_ACREEDORES_PA_PAISES`
    FOREIGN KEY (`PAIS_ID`)
    REFERENCES `softpacbd`.`PA_PAISES` (`PAIS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_ACREEDORES_PA_USUARIOS`
    FOREIGN KEY (`USUARIO_ELIMINACION`)
    REFERENCES `softpacbd`.`PA_USUARIOS` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_ENTIDADES_BANCARIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_ENTIDADES_BANCARIAS` (
  `ENTIDAD_BANCARIA_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `FORMATO_ACEPTADO` VARCHAR(50) NOT NULL,
  `CODIGO_SWIFT` CHAR(11) NOT NULL,
  `PAIS_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ENTIDAD_BANCARIA_ID`),
  INDEX `IDX_PA_ENTIDADES_BANCARIAS_PAIS_ID` (`PAIS_ID` ASC) INVISIBLE,
  CONSTRAINT `FK_PA_ENTIDADES_BANCARIAS_PA_PAISES`
    FOREIGN KEY (`PAIS_ID`)
    REFERENCES `softpacbd`.`PA_PAISES` (`PAIS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_MONEDAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_MONEDAS` (
  `MONEDA_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `CODIGO_ISO` CHAR(3) NOT NULL,
  `SIMBOLO` CHAR(3) NOT NULL,
  PRIMARY KEY (`MONEDA_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_CUENTAS_ACREEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_CUENTAS_ACREEDOR` (
  `CUENTA_ACREEDOR_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TIPO_CUENTA` VARCHAR(45) NOT NULL,
  `NUMERO_CUENTA` VARCHAR(45) NOT NULL,
  `CCI` VARCHAR(45) NOT NULL,
  `ACTIVO` CHAR(1) NOT NULL DEFAULT 'S',
  `ACREEDOR_ID` INT UNSIGNED NOT NULL,
  `ENTIDAD_BANCARIA_ID` INT UNSIGNED NOT NULL,
  `MONEDA_ID` INT UNSIGNED NOT NULL,
  `FECHA_ELIMINACION` DATETIME NULL,
  `USUARIO_ELIMINACION` INT NULL,
  PRIMARY KEY (`CUENTA_ACREEDOR_ID`),
  INDEX `IDX_PA_CUENTAS_ACREEDOR_ACREEDOR_ID` (`ACREEDOR_ID` ASC) VISIBLE,
  UNIQUE INDEX `UQ_PA_CUENTAS_ACREEDOR_NUMERO_CUENTA` (`NUMERO_CUENTA` ASC) VISIBLE,
  INDEX `fk_PA_CUENTAS_ACREEDOR_PA_ENTIDADES_BANCARIAS1_idx` (`ENTIDAD_BANCARIA_ID` ASC) VISIBLE,
  INDEX `fk_PA_CUENTAS_ACREEDOR_PA_MONEDAS1_idx` (`MONEDA_ID` ASC) VISIBLE,
  INDEX `fk_PA_CUENTAS_ACREEDOR_PA_USUARIOS1_idx` (`USUARIO_ELIMINACION` ASC) VISIBLE,
  CONSTRAINT `FK_PA_CUENTAS_ACREEDOR_PA_ACREEDORES1`
    FOREIGN KEY (`ACREEDOR_ID`)
    REFERENCES `softpacbd`.`PA_ACREEDORES` (`ACREEDOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_CUENTAS_ACREEDOR_PA_ENTIDADES_BANCARIAS`
    FOREIGN KEY (`ENTIDAD_BANCARIA_ID`)
    REFERENCES `softpacbd`.`PA_ENTIDADES_BANCARIAS` (`ENTIDAD_BANCARIA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_CUENTAS_ACREEDOR_PA_MONEDAS`
    FOREIGN KEY (`MONEDA_ID`)
    REFERENCES `softpacbd`.`PA_MONEDAS` (`MONEDA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_CUENTAS_ACREEDOR_PA_USUARIOS`
    FOREIGN KEY (`USUARIO_ELIMINACION`)
    REFERENCES `softpacbd`.`PA_USUARIOS` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_CUENTAS_PROPIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_CUENTAS_PROPIAS` (
  `CUENTA_PROPIA_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `SALDO_DISPONIBLE` DECIMAL(15,2) NOT NULL DEFAULT 0.0,
  `TIPO_CUENTA` VARCHAR(45) NOT NULL,
  `NUMERO_CUENTA` VARCHAR(45) NOT NULL,
  `CCI` VARCHAR(45) NOT NULL,
  `ACTIVO` CHAR(1) NOT NULL DEFAULT 'S',
  `ENTIDAD_BANCARIA_ID` INT UNSIGNED NOT NULL,
  `MONEDA_ID` INT UNSIGNED NOT NULL,
  `FECHA_ELIMINACION` DATETIME NULL,
  `USUARIO_ELIMINACION` INT NULL,
  PRIMARY KEY (`CUENTA_PROPIA_ID`),
  INDEX `fk_PA_CUENTAS_PROPIAS_PA_ENTIDADES_BANCARIAS1_idx` (`ENTIDAD_BANCARIA_ID` ASC) VISIBLE,
  INDEX `fk_PA_CUENTAS_PROPIAS_PA_MONEDAS1_idx` (`MONEDA_ID` ASC) VISIBLE,
  UNIQUE INDEX `UQ_PA_CUENTAS_PROPIAS_NUMERO_CUENTA` (`NUMERO_CUENTA` ASC) VISIBLE,
  INDEX `fk_PA_CUENTAS_PROPIAS_PA_USUARIOS1_idx` (`USUARIO_ELIMINACION` ASC) VISIBLE,
  CONSTRAINT `FK_PA_CUENTAS_PROPIAS_PA_ENTIDADES_BANCARIAS`
    FOREIGN KEY (`ENTIDAD_BANCARIA_ID`)
    REFERENCES `softpacbd`.`PA_ENTIDADES_BANCARIAS` (`ENTIDAD_BANCARIA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_CUENTAS_PROPIAS_PA_MONEDAS`
    FOREIGN KEY (`MONEDA_ID`)
    REFERENCES `softpacbd`.`PA_MONEDAS` (`MONEDA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_CUENTAS_PROPIAS_PA_USUARIOS`
    FOREIGN KEY (`USUARIO_ELIMINACION`)
    REFERENCES `softpacbd`.`PA_USUARIOS` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_FACTURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_FACTURAS` (
  `FACTURA_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NUMERO_FACTURA` VARCHAR(45) NOT NULL,
  `FECHA_EMISION` DATETIME NOT NULL,
  `FECHA_RECEPCION` DATETIME NOT NULL,
  `FECHA_LIMITE_PAGO` DATETIME NOT NULL,
  `ESTADO` VARCHAR(25) NOT NULL DEFAULT 'PENDIENTE',
  `MONTO_TOTAL` DECIMAL(15,2) NOT NULL,
  `MONTO_IGV` DECIMAL(15,2) NOT NULL,
  `MONTO_RESTANTE` DECIMAL(15,2) NOT NULL,
  `REGIMEN_FISCAL` VARCHAR(30) NOT NULL,
  `TASA_IVA` DECIMAL(15,2) NULL,
  `OTROS_TRIBUTOS` DECIMAL(15,2) NULL,
  `MONEDA_ID` INT UNSIGNED NOT NULL,
  `ACREEDOR_ID` INT UNSIGNED NOT NULL,
  `FECHA_ELIMINACION` DATETIME NULL,
  `USUARIO_ELIMINACION` INT NULL,
  PRIMARY KEY (`FACTURA_ID`),
  UNIQUE INDEX `UQ_PA_FACTURAS_NUMERO_FACTURA` (`NUMERO_FACTURA` ASC) VISIBLE,
  INDEX `IDX_PA_FACTURAS_ACREEDOR_ID` (`ACREEDOR_ID` ASC) VISIBLE,
  INDEX `IDX_PA_FACTURAS_MONEDA_ID` (`MONEDA_ID` ASC) VISIBLE,
  INDEX `fk_PA_FACTURAS_PA_USUARIOS1_idx` (`USUARIO_ELIMINACION` ASC) VISIBLE,
  CONSTRAINT `FK_PA_FACTURAS_PA_ACREEDORES`
    FOREIGN KEY (`ACREEDOR_ID`)
    REFERENCES `softpacbd`.`PA_ACREEDORES` (`ACREEDOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_FACTURAS_PA_MONEDAS`
    FOREIGN KEY (`MONEDA_ID`)
    REFERENCES `softpacbd`.`PA_MONEDAS` (`MONEDA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_FACTURAS_PA_USUARIOS`
    FOREIGN KEY (`USUARIO_ELIMINACION`)
    REFERENCES `softpacbd`.`PA_USUARIOS` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_PROPUESTAS_DE_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_PROPUESTAS_DE_PAGO` (
  `PROPUESTA_DE_PAGO_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FECHA_HORA_CREACION` DATETIME NOT NULL,
  `ESTADO` VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  `ENTIDAD_BANCARIA_ID` INT UNSIGNED NOT NULL,
  `FECHA_HORA_MODIFICACION` DATETIME NOT NULL,
  `USUARIO_MODIFICACION` INT NOT NULL,
  `USUARIO_CREACION` INT NOT NULL,
  `FECHA_ELIMINACION` DATETIME NULL,
  `USUARIO_ELIMINACION` INT NULL,
  PRIMARY KEY (`PROPUESTA_DE_PAGO_ID`),
  INDEX `IDX_PA_PROPUESTAS_DE_PAGO_ENTIDAD_BANCARIA_ID` (`ENTIDAD_BANCARIA_ID` ASC) VISIBLE,
  INDEX `fk_PA_PROPUESTAS_DE_PAGO_PA_USUARIOS1_idx` (`USUARIO_ELIMINACION` ASC) VISIBLE,
  INDEX `fk_PA_PROPUESTAS_DE_PAGO_PA_USUARIOS1_idx1` (`USUARIO_MODIFICACION` ASC) VISIBLE,
  INDEX `fk_PA_PROPUESTAS_DE_PAGO_PA_USUARIOS1_idx2` (`USUARIO_CREACION` ASC) VISIBLE,
  CONSTRAINT `FK_PA_PROPUESTAS_DE_PAGO_PA_ENTIDADES_BANCARIAS`
    FOREIGN KEY (`ENTIDAD_BANCARIA_ID`)
    REFERENCES `softpacbd`.`PA_ENTIDADES_BANCARIAS` (`ENTIDAD_BANCARIA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_PROPUESTAS_DE_PAGO_PA_USUARIOS1`
    FOREIGN KEY (`USUARIO_ELIMINACION`)
    REFERENCES `softpacbd`.`PA_USUARIOS` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_PROPUESTAS_DE_PAGO_PA_USUARIOS2`
    FOREIGN KEY (`USUARIO_MODIFICACION`)
    REFERENCES `softpacbd`.`PA_USUARIOS` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_PROPUESTAS_DE_PAGO_PA_USUARIOS3`
    FOREIGN KEY (`USUARIO_CREACION`)
    REFERENCES `softpacbd`.`PA_USUARIOS` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_DETALLES_PROPUESTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_DETALLES_PROPUESTA` (
  `DETALLE_PROPUESTA_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MONTO_PAGO` DECIMAL(15,2) NOT NULL,
  `FORMA_PAGO` CHAR(1) NOT NULL,
  `PROPUESTA_DE_PAGO_ID` INT UNSIGNED NOT NULL,
  `FACTURA_ID` INT UNSIGNED NOT NULL,
  `CUENTA_ACREEDOR_ID` INT UNSIGNED NOT NULL,
  `CUENTA_PROPIA_ID` INT UNSIGNED NOT NULL,
  `FECHA_ELIMINACION` DATETIME NULL,
  `USUARIO_ELIMINACION` INT NULL,
  PRIMARY KEY (`DETALLE_PROPUESTA_ID`),
  INDEX `IDX_PA_DETALLES_PROPUESTA_PROPUESTA_DE_PAGO_ID` (`PROPUESTA_DE_PAGO_ID` ASC) VISIBLE,
  INDEX `IDX_PA_DETALLES_PROPUESTA_FACTURA_ID` (`FACTURA_ID` ASC) VISIBLE,
  INDEX `IDX_PA_DETALLES_PROPUESTA_CUENTA_ACREEDOR_ID` (`CUENTA_ACREEDOR_ID` ASC) VISIBLE,
  INDEX `IDX_PA_DETALLES_PROPUESTA_CUENTA_PROPIA_ID` (`CUENTA_PROPIA_ID` ASC) INVISIBLE,
  UNIQUE INDEX `UQ_PA_DETALLES_PROPUESTA_PROPUESTA_FACTURA` (`PROPUESTA_DE_PAGO_ID` ASC, `FACTURA_ID` ASC) VISIBLE,
  INDEX `fk_PA_DETALLES_PROPUESTA_PA_USUARIOS1_idx` (`USUARIO_ELIMINACION` ASC) VISIBLE,
  CONSTRAINT `FK_PA_DETALLES_PROPUESTA_PA_PROPUESTAS_DE_PAGO`
    FOREIGN KEY (`PROPUESTA_DE_PAGO_ID`)
    REFERENCES `softpacbd`.`PA_PROPUESTAS_DE_PAGO` (`PROPUESTA_DE_PAGO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_DETALLES_PROPUESTA_PA_FACTURAS`
    FOREIGN KEY (`FACTURA_ID`)
    REFERENCES `softpacbd`.`PA_FACTURAS` (`FACTURA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_DETALLES_PROPUESTA_PA_CUENTAS_ACREEDOR`
    FOREIGN KEY (`CUENTA_ACREEDOR_ID`)
    REFERENCES `softpacbd`.`PA_CUENTAS_ACREEDOR` (`CUENTA_ACREEDOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_DETALLES_PROPUESTA_PA_CUENTAS_PROPIAS`
    FOREIGN KEY (`CUENTA_PROPIA_ID`)
    REFERENCES `softpacbd`.`PA_CUENTAS_PROPIAS` (`CUENTA_PROPIA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_DETALLES_PROPUESTA_PA_USUARIOS`
    FOREIGN KEY (`USUARIO_ELIMINACION`)
    REFERENCES `softpacbd`.`PA_USUARIOS` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_DETALLES_FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_DETALLES_FACTURA` (
  `DETALLE_FACTURA_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `SUBTOTAL` DECIMAL(15,2) NOT NULL,
  `DESCRIPCION` VARCHAR(125) NOT NULL,
  `FACTURA_ID` INT UNSIGNED NOT NULL,
  `FECHA_ELIMINACION` DATETIME NULL,
  `USUARIO_ELIMINACION` INT NULL,
  PRIMARY KEY (`DETALLE_FACTURA_ID`),
  INDEX `IDX_PA_DETALLES_FACTURA_FACTURA_ID` (`FACTURA_ID` ASC) VISIBLE,
  INDEX `fk_PA_DETALLES_FACTURA_PA_USUARIOS1_idx` (`USUARIO_ELIMINACION` ASC) VISIBLE,
  CONSTRAINT `FK_PA_DETALLES_FACTURA_PA_FACTURAS`
    FOREIGN KEY (`FACTURA_ID`)
    REFERENCES `softpacbd`.`PA_FACTURAS` (`FACTURA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_DETALLES_FACTURA_PA_USUARIOS`
    FOREIGN KEY (`USUARIO_ELIMINACION`)
    REFERENCES `softpacbd`.`PA_USUARIOS` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_TIPOS_DE_CAMBIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_TIPOS_DE_CAMBIO` (
  `TIPO_CAMBIO_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FECHA_HORA` DATETIME NOT NULL,
  `TASA_DE_CAMBIO` DECIMAL(12,6) NOT NULL,
  `MONEDA_ORIGEN_ID` INT UNSIGNED NOT NULL,
  `MONEDA_DESTINO_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`TIPO_CAMBIO_ID`),
  INDEX `IDX_PA_TIPOS_DE_CAMBIO_MONEDA_ORIGEN_ID` (`MONEDA_ORIGEN_ID` ASC) VISIBLE,
  INDEX `IDX_PA_TIPOS_DE_CAMBIO_MONEDA_DESTINO_ID` (`MONEDA_DESTINO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PA_TIPOS_DE_CAMBIO_PA_MONEDAS_ORIG`
    FOREIGN KEY (`MONEDA_ORIGEN_ID`)
    REFERENCES `softpacbd`.`PA_MONEDAS` (`MONEDA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_TIPOS_DE_CAMBIO_PA_MONEDAS_DEST`
    FOREIGN KEY (`MONEDA_DESTINO_ID`)
    REFERENCES `softpacbd`.`PA_MONEDAS` (`MONEDA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_REPORTES_FACTURAS_PENDIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_REPORTES_FACTURAS_PENDIENTES` (
  `FACTURA_ID` INT UNSIGNED NOT NULL,
  `ACREEDOR_ID` INT UNSIGNED NOT NULL,
  `PAIS_ID` INT UNSIGNED NOT NULL,
  `MONEDA_ID` INT UNSIGNED NOT NULL,
  `NUMERO_FACTURA` VARCHAR(45) NOT NULL,
  `RAZON_SOCIAL` VARCHAR(200) NOT NULL,
  `NOMBRE_PAIS` VARCHAR(60) NOT NULL,
  `CODIGO_MONEDA` CHAR(3) NOT NULL,
  `FECHA_LIMITE_PAGO` DATETIME NOT NULL,
  `DIAS_VENCIMIENTO` INT NOT NULL,
  `RANGO_VENCIMIENTO` VARCHAR(10) NOT NULL,
  `MONTO_RESTANTE` DECIMAL(15,2) NOT NULL,
  INDEX `fk_PA_REPORTES_FACTURAS_PENDIENTES_PA_FACTURAS1_idx` (`FACTURA_ID` ASC) VISIBLE,
  PRIMARY KEY (`FACTURA_ID`, `ACREEDOR_ID`),
  INDEX `fk_PA_REPORTES_FACTURAS_PENDIENTES_PA_ACREEDORES1_idx` (`ACREEDOR_ID` ASC) VISIBLE,
  INDEX `fk_PA_REPORTES_FACTURAS_PENDIENTES_PA_PAISES1_idx` (`PAIS_ID` ASC) VISIBLE,
  INDEX `fk_PA_REPORTES_FACTURAS_PENDIENTES_PA_MONEDAS1_idx` (`MONEDA_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PA_REPORTES_FACTURAS_PENDIENTES_PA_FACTURAS`
    FOREIGN KEY (`FACTURA_ID`)
    REFERENCES `softpacbd`.`PA_FACTURAS` (`FACTURA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_REPORTES_FACTURAS_PENDIENTES_PA_ACREEDORES`
    FOREIGN KEY (`ACREEDOR_ID`)
    REFERENCES `softpacbd`.`PA_ACREEDORES` (`ACREEDOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_REPORTES_FACTURAS_PENDIENTES_PA_PAISES`
    FOREIGN KEY (`PAIS_ID`)
    REFERENCES `softpacbd`.`PA_PAISES` (`PAIS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_REPORTES_FACTURAS_PENDIENTES_PA_MONEDAS`
    FOREIGN KEY (`MONEDA_ID`)
    REFERENCES `softpacbd`.`PA_MONEDAS` (`MONEDA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softpacbd`.`PA_REPORTE_PROPUESTAS_DE_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`PA_REPORTE_PROPUESTAS_DE_PAGO` (
  `PROPUESTA_DE_PAGO_ID` INT UNSIGNED NOT NULL,
  `DETALLE_PROPUESTA_ID` INT UNSIGNED NOT NULL,
  `ACREEDOR_ID` INT UNSIGNED NOT NULL,
  `CUENTA_ACREEDOR_ID` INT UNSIGNED NOT NULL,
  `CUENTA_PROPIA_ID` INT UNSIGNED NOT NULL,
  `ENTIDAD_BANCARIA_ID` INT UNSIGNED NOT NULL,
  `PAIS_ID` INT UNSIGNED NOT NULL,
  `MONEDA_ID` INT UNSIGNED NOT NULL,
  `MONTO_PAGO` DECIMAL(15,2) NOT NULL,
  `CODIGO_MONEDA` CHAR(3) NOT NULL,
  `RAZON_SOCIAL` VARCHAR(200) NOT NULL,
  `NUMERO_CUENTA_ACREEDOR` VARCHAR(45) NOT NULL,
  `NUMERO_CUENTA_PROPIA` VARCHAR(45) NOT NULL,
  `NOMBRE_ENTIDAD_BANCARIA` VARCHAR(100) NOT NULL,
  `NOMBRE_PAIS` VARCHAR(60) NOT NULL,
  INDEX `fk_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_PROPUESTAS_DE_PAGO1_idx` (`PROPUESTA_DE_PAGO_ID` ASC) VISIBLE,
  INDEX `fk_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_DETALLES_PROPUESTA1_idx` (`DETALLE_PROPUESTA_ID` ASC) VISIBLE,
  INDEX `fk_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_ACREEDORES1_idx` (`ACREEDOR_ID` ASC) VISIBLE,
  INDEX `fk_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_CUENTAS_ACREEDOR1_idx` (`CUENTA_ACREEDOR_ID` ASC) VISIBLE,
  INDEX `fk_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_CUENTAS_PROPIAS1_idx` (`CUENTA_PROPIA_ID` ASC) VISIBLE,
  INDEX `fk_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_ENTIDADES_BANCARIAS1_idx` (`ENTIDAD_BANCARIA_ID` ASC) VISIBLE,
  INDEX `fk_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_PAISES1_idx` (`PAIS_ID` ASC) VISIBLE,
  INDEX `fk_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_MONEDAS1_idx` (`MONEDA_ID` ASC) VISIBLE,
  PRIMARY KEY (`PROPUESTA_DE_PAGO_ID`, `DETALLE_PROPUESTA_ID`),
  CONSTRAINT `FK_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_PROPUESTAS_DE_PAGO`
    FOREIGN KEY (`PROPUESTA_DE_PAGO_ID`)
    REFERENCES `softpacbd`.`PA_PROPUESTAS_DE_PAGO` (`PROPUESTA_DE_PAGO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_DETALLES_PROPUESTA`
    FOREIGN KEY (`DETALLE_PROPUESTA_ID`)
    REFERENCES `softpacbd`.`PA_DETALLES_PROPUESTA` (`DETALLE_PROPUESTA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_ACREEDORES`
    FOREIGN KEY (`ACREEDOR_ID`)
    REFERENCES `softpacbd`.`PA_ACREEDORES` (`ACREEDOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_CUENTAS_ACREEDOR`
    FOREIGN KEY (`CUENTA_ACREEDOR_ID`)
    REFERENCES `softpacbd`.`PA_CUENTAS_ACREEDOR` (`CUENTA_ACREEDOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_CUENTAS_PROPIAS`
    FOREIGN KEY (`CUENTA_PROPIA_ID`)
    REFERENCES `softpacbd`.`PA_CUENTAS_PROPIAS` (`CUENTA_PROPIA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_ENTIDADES_BANCARIAS`
    FOREIGN KEY (`ENTIDAD_BANCARIA_ID`)
    REFERENCES `softpacbd`.`PA_ENTIDADES_BANCARIAS` (`ENTIDAD_BANCARIA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_PAISES`
    FOREIGN KEY (`PAIS_ID`)
    REFERENCES `softpacbd`.`PA_PAISES` (`PAIS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PA_REPORTE_PROPUESTAS_DE_PAGO_PA_MONEDAS`
    FOREIGN KEY (`MONEDA_ID`)
    REFERENCES `softpacbd`.`PA_MONEDAS` (`MONEDA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `softpacbd` ;

-- -----------------------------------------------------
-- Placeholder table for view `softpacbd`.`VW_DETALLE_PROPUESTA_COMPLETO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`VW_DETALLE_PROPUESTA_COMPLETO` (`PROPUESTA_DE_PAGO_ID` INT, `FECHA_HORA_CREACION` INT, `ESTADO` INT, `PROPUESTA_ENTIDAD_ID` INT, `PROPUESTA_BANCO` INT, `PROPUESTA_SWIFT` INT, `PROPUESTA_PAIS_ID` INT, `PROPUESTA_PAIS_NOMBRE` INT, `PROPUESTA_PAIS_ISO` INT, `PROPUESTA_PAIS_TELEFONO` INT, `DETALLE_PROPUESTA_ID` INT, `MONTO_PAGO` INT, `FORMA_PAGO` INT, `FACTURA_ID` INT, `NUMERO_FACTURA` INT, `FECHA_EMISION` INT, `FECHA_RECEPCION` INT, `FECHA_LIMITE_PAGO` INT, `FACTURA_ESTADO` INT, `MONTO_TOTAL` INT, `MONTO_IGV` INT, `MONTO_RESTANTE` INT, `REGIMEN_FISCAL` INT, `TASA_IVA` INT, `OTROS_TRIBUTOS` INT, `FACTURA_MONEDA_ID` INT, `FACTURA_ACREEDOR_ID` INT, `CUENTA_ACREEDOR_ID` INT, `CUENTA_ACREEDOR_TIPO` INT, `CUENTA_ACREEDOR_NUMERO` INT, `CUENTA_ACREEDOR_CCI` INT, `CUENTA_ACREEDOR_ACTIVA` INT, `CUENTA_ACREEDOR_ACREEDOR_ID` INT, `CUENTA_ACREEDOR_MONEDA_ID` INT, `BANCO_ACREEDOR_ID` INT, `BANCO_ACREEDOR_NOMBRE` INT, `BANCO_ACREEDOR_SWIFT` INT, `BANCO_ACREEDOR_PAIS_ID` INT, `BANCO_ACREEDOR_PAIS_NOMBRE` INT, `BANCO_ACREEDOR_PAIS_ISO` INT, `BANCO_ACREEDOR_PAIS_TELEFONO` INT, `CUENTA_PROPIA_ID` INT, `SALDO_DISPONIBLE` INT, `CUENTA_PROPIA_TIPO` INT, `CUENTA_PROPIA_NUMERO` INT, `CUENTA_PROPIA_CCI` INT, `CUENTA_PROPIA_ACTIVA` INT, `CUENTA_PROPIA_MONEDA_ID` INT, `BANCO_PROPIO_ID` INT, `BANCO_PROPIO_NOMBRE` INT, `BANCO_PROPIO_SWIFT` INT, `BANCO_PROPIO_PAIS_ID` INT, `BANCO_PROPIO_PAIS_NOMBRE` INT, `BANCO_PROPIO_PAIS_ISO` INT, `BANCO_PROPIO_PAIS_TELEFONO` INT);

-- -----------------------------------------------------
-- Placeholder table for view `softpacbd`.`VW_FACTURA_COMPLETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`VW_FACTURA_COMPLETA` (`FACTURA_ID` INT, `NUMERO_FACTURA` INT, `FECHA_EMISION` INT, `FECHA_RECEPCION` INT, `FECHA_LIMITE_PAGO` INT, `ESTADO` INT, `MONTO_TOTAL` INT, `MONTO_IGV` INT, `MONTO_RESTANTE` INT, `REGIMEN_FISCAL` INT, `TASA_IVA` INT, `OTROS_TRIBUTOS` INT, `MONEDA_ID` INT, `MONEDA_NOMBRE` INT, `MONEDA_CODIGO_ISO` INT, `MONEDA_SIMBOLO` INT, `ACREEDOR_ID` INT, `ACREEDOR_RAZON_SOCIAL` INT, `ACREEDOR_RUC` INT, `ACREEDOR_DIRECCION_FISCAL` INT, `ACREEDOR_CONDICION` INT, `ACREEDOR_PLAZO_DE_PAGO` INT, `ACREEDOR_ACTIVO` INT, `PAIS_ID` INT, `PAIS_NOMBRE` INT, `DETALLE_FACTURA_ID` INT, `DETALLE_SUBTOTAL` INT, `DETALLE_DESCRIPCION` INT);

-- -----------------------------------------------------
-- Placeholder table for view `softpacbd`.`VW_PROPUESTA_COMPLETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softpacbd`.`VW_PROPUESTA_COMPLETA` (`P1_PROPUESTA_DE_PAGO_ID` INT, `P2_FECHA_HORA_CREACION` INT, `P3_FECHA_HORA_MODIFICACION` INT, `P4_USUARIO_CREACION` INT, `P5_USUARIO_CREACION_CORREO` INT, `P6_USUARIO_CREACION_NOMBRE_USUARIO` INT, `P7_USUARIO_CREACION_NOMBRE` INT, `P8_USUARIO_CREACION_APELLIDOS` INT, `P9_USUARIO_CREACION_ACTIVO` INT, `P10_USUARIO_CREACION_SUPERUSUARIO` INT, `P11_USUARIO_MODIFICACION` INT, `P12_USUARIO_MODIFICACION_CORREO` INT, `P13_USUARIO_MODIFICACION_NOMBRE_USUARIO` INT, `P14_USUARIO_MODIFICACION_NOMBRE` INT, `P15_USUARIO_MODIFICACION_APELLIDOS` INT, `P16_USUARIO_MODIFICACION_ACTIVO` INT, `P17_USUARIO_MODIFICACION_SUPERUSUARIO` INT, `P18_ESTADO_PROPUESTA` INT, `P19_ENTIDAD_BANCARIA_PROPUESTA` INT, `P20_ENTIDAD_BANCARIA_NOMBRE` INT, `P21_ENTIDAD_BANCARIA_FORMATO` INT, `P22_ENTIDAD_BANCARIA_SWIFT` INT, `P23_ENTIDAD_BANCARIA_PAIS_ID` INT, `P24_ENTIDAD_BANCARIA_PAIS_NOMBRE` INT, `D1_DETALLE_PROPUESTA_ID` INT, `D2_MONTO_PAGO` INT, `D3_FORMA_PAGO` INT, `F1_FACTURA_ID` INT, `F2_NUMERO_FACTURA` INT, `F3_FECHA_EMISION` INT, `F4_FECHA_RECEPCION` INT, `F5_FECHA_LIMITE_PAGO` INT, `F6_ESTADO_FACTURA` INT, `F7_MONTO_TOTAL` INT, `F8_MONTO_IGV` INT, `F9_MONTO_RESTANTE` INT, `F10_REGIMEN_FISCAL` INT, `F11_TASA_IVA` INT, `F12_OTROS_TRIBUTOS` INT, `F13_MONEDA_ID` INT, `F14_ACREEDOR_ID` INT, `CA1_CUENTA_ACREEDOR_ID` INT, `CA2_TIPO_CUENTA` INT, `CA3_NUMERO_CUENTA` INT, `CA4_CCI` INT, `CA5_ACTIVO` INT, `CA6_ACREEDOR_ID` INT, `CA7_ENTIDAD_BANCARIA_ID` INT, `CA8_MONEDA_ID` INT, `CA9_ENTIDAD_BANCARIA_NOMBRE` INT, `CA10_ENTIDAD_BANCARIA_SWIFT` INT, `CA11_ENTIDAD_BANCARIA_PAIS_ID` INT, `CA12_ENTIDAD_BANCARIA_PAIS_NOMBRE` INT, `CP1_CUENTA_PROPIA_ID` INT, `CP2_SALDO_DISPONIBLE` INT, `CP3_TIPO_CUENTA` INT, `CP4_NUMERO_CUENTA` INT, `CP5_CCI` INT, `CP6_ACTIVO` INT, `CP7_ENTIDAD_BANCARIA_ID` INT, `CP8_MONEDA_ID` INT, `CP9_ENTIDAD_BANCARIA_NOMBRE` INT, `CP10_ENTIDAD_BANCARIA_SWIFT` INT, `CP11_ENTIDAD_BANCARIA_PAIS_ID` INT, `CP12_ENTIDAD_BANCARIA_PAIS_NOMBRE` INT);

-- -----------------------------------------------------
-- View `softpacbd`.`VW_DETALLE_PROPUESTA_COMPLETO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softpacbd`.`VW_DETALLE_PROPUESTA_COMPLETO`;
USE `softpacbd`;
CREATE OR REPLACE VIEW `VW_DETALLE_PROPUESTA_COMPLETO` AS
SELECT 
    -- Propuesta
    p.PROPUESTA_DE_PAGO_ID,
    p.FECHA_HORA_CREACION,
    p.ESTADO,
    ebp.ENTIDAD_BANCARIA_ID       AS PROPUESTA_ENTIDAD_ID,
    ebp.NOMBRE                    AS PROPUESTA_BANCO,
    ebp.CODIGO_SWIFT              AS PROPUESTA_SWIFT,
    pbp.PAIS_ID                   AS PROPUESTA_PAIS_ID,
    pbp.NOMBRE                    AS PROPUESTA_PAIS_NOMBRE,
    pbp.CODIGO_ISO                AS PROPUESTA_PAIS_ISO,
    pbp.CODIGO_TELEFONICO         AS PROPUESTA_PAIS_TELEFONO,

    -- Detalle de propuesta
    dp.DETALLE_PROPUESTA_ID       AS DETALLE_PROPUESTA_ID,
    dp.MONTO_PAGO,
    dp.FORMA_PAGO,

    -- Factura
    f.FACTURA_ID,
    f.NUMERO_FACTURA,
    f.FECHA_EMISION,
    f.FECHA_RECEPCION,
    f.FECHA_LIMITE_PAGO,
    f.ESTADO                      AS FACTURA_ESTADO,
    f.MONTO_TOTAL,
    f.MONTO_IGV,
    f.MONTO_RESTANTE,
    f.REGIMEN_FISCAL,
    f.TASA_IVA,
    f.OTROS_TRIBUTOS,
    f.MONEDA_ID                   AS FACTURA_MONEDA_ID,
    f.ACREEDOR_ID                 AS FACTURA_ACREEDOR_ID,

    -- Cuenta del acreedor (destino)
    ca.CUENTA_ACREEDOR_ID,
    ca.TIPO_CUENTA                AS CUENTA_ACREEDOR_TIPO,
    ca.NUMERO_CUENTA              AS CUENTA_ACREEDOR_NUMERO,
    ca.CCI                        AS CUENTA_ACREEDOR_CCI,
    ca.ACTIVO                     AS CUENTA_ACREEDOR_ACTIVA,
    ca.ACREEDOR_ID                AS CUENTA_ACREEDOR_ACREEDOR_ID,
	ca.MONEDA_ID				  AS CUENTA_ACREEDOR_MONEDA_ID,
    eba.ENTIDAD_BANCARIA_ID       AS BANCO_ACREEDOR_ID,
    eba.NOMBRE                    AS BANCO_ACREEDOR_NOMBRE,
    eba.CODIGO_SWIFT              AS BANCO_ACREEDOR_SWIFT,
    pba.PAIS_ID                   AS BANCO_ACREEDOR_PAIS_ID,
    pba.NOMBRE                    AS BANCO_ACREEDOR_PAIS_NOMBRE,
    pba.CODIGO_ISO                AS BANCO_ACREEDOR_PAIS_ISO,
    pba.CODIGO_TELEFONICO         AS BANCO_ACREEDOR_PAIS_TELEFONO,

    -- Cuenta propia (origen)
    cp.CUENTA_PROPIA_ID,
    cp.SALDO_DISPONIBLE,
    cp.TIPO_CUENTA                AS CUENTA_PROPIA_TIPO,
    cp.NUMERO_CUENTA              AS CUENTA_PROPIA_NUMERO,
    cp.CCI                        AS CUENTA_PROPIA_CCI,
    cp.ACTIVO                     AS CUENTA_PROPIA_ACTIVA,
	cp.MONEDA_ID				  AS CUENTA_PROPIA_MONEDA_ID,
    ebo.ENTIDAD_BANCARIA_ID       AS BANCO_PROPIO_ID,
    ebo.NOMBRE                    AS BANCO_PROPIO_NOMBRE,
    ebo.CODIGO_SWIFT              AS BANCO_PROPIO_SWIFT,
    pbo.PAIS_ID                   AS BANCO_PROPIO_PAIS_ID,
    pbo.NOMBRE                    AS BANCO_PROPIO_PAIS_NOMBRE,
    pbo.CODIGO_ISO                AS BANCO_PROPIO_PAIS_ISO,
    pbo.CODIGO_TELEFONICO         AS BANCO_PROPIO_PAIS_TELEFONO

FROM PA_DETALLES_PROPUESTA dp
JOIN PA_PROPUESTAS_DE_PAGO p 
    ON p.PROPUESTA_DE_PAGO_ID = dp.PROPUESTA_DE_PAGO_ID
JOIN PA_ENTIDADES_BANCARIAS ebp 
    ON ebp.ENTIDAD_BANCARIA_ID = p.ENTIDAD_BANCARIA_ID
JOIN PA_PAISES pbp 
    ON pbp.PAIS_ID = ebp.PAIS_ID

JOIN PA_FACTURAS f 
    ON f.FACTURA_ID = dp.FACTURA_ID

JOIN PA_CUENTAS_ACREEDOR ca 
    ON ca.CUENTA_ACREEDOR_ID = dp.CUENTA_ACREEDOR_ID
JOIN PA_ENTIDADES_BANCARIAS eba 
    ON eba.ENTIDAD_BANCARIA_ID = ca.ENTIDAD_BANCARIA_ID
JOIN PA_PAISES pba 
    ON pba.PAIS_ID = eba.PAIS_ID

JOIN PA_CUENTAS_PROPIAS cp 
    ON cp.CUENTA_PROPIA_ID = dp.CUENTA_PROPIA_ID
JOIN PA_ENTIDADES_BANCARIAS ebo 
    ON ebo.ENTIDAD_BANCARIA_ID = cp.ENTIDAD_BANCARIA_ID
JOIN PA_PAISES pbo 
    ON pbo.PAIS_ID = ebo.PAIS_ID;

-- -----------------------------------------------------
-- View `softpacbd`.`VW_FACTURA_COMPLETA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softpacbd`.`VW_FACTURA_COMPLETA`;
USE `softpacbd`;
-- Crea o reemplaza la vista que reúne cabecera, moneda, acreedor, país y detalles
CREATE OR REPLACE VIEW VW_FACTURA_COMPLETA AS
SELECT
  /*  1 */ f.FACTURA_ID                          AS FACTURA_ID,
  /*  2 */ f.NUMERO_FACTURA                      AS NUMERO_FACTURA,
  /*  3 */ f.FECHA_EMISION                       AS FECHA_EMISION,
  /*  4 */ f.FECHA_RECEPCION                     AS FECHA_RECEPCION,
  /*  5 */ f.FECHA_LIMITE_PAGO                   AS FECHA_LIMITE_PAGO,
  /*  6 */ f.ESTADO                              AS ESTADO,
  /*  7 */ f.MONTO_TOTAL                         AS MONTO_TOTAL,
  /*  8 */ f.MONTO_IGV                           AS MONTO_IGV,
  /*  9 */ f.MONTO_RESTANTE                      AS MONTO_RESTANTE,
  /* 10 */ f.REGIMEN_FISCAL                      AS REGIMEN_FISCAL,
  /* 11 */ f.TASA_IVA                            AS TASA_IVA,          
  /* 12 */ f.OTROS_TRIBUTOS                      AS OTROS_TRIBUTOS,
  /* Moneda */
  /* 13 */ m.MONEDA_ID                           AS MONEDA_ID,
  /* 14 */ m.NOMBRE                              AS MONEDA_NOMBRE,
  /* 15 */ m.CODIGO_ISO                          AS MONEDA_CODIGO_ISO,
  /* 16 */ m.SIMBOLO                             AS MONEDA_SIMBOLO,
  /* Acreedor */
  /* 17 */ a.ACREEDOR_ID                         AS ACREEDOR_ID,
  /* 18 */ a.RAZON_SOCIAL                        AS ACREEDOR_RAZON_SOCIAL,
  /* 19 */ a.RUC                                 AS ACREEDOR_RUC,
  /* 20 */ a.DIRECCION_FISCAL                    AS ACREEDOR_DIRECCION_FISCAL,
  /* 21 */ a.CONDICION                           AS ACREEDOR_CONDICION,
  /* 22 */ a.PLAZO_DE_PAGO                       AS ACREEDOR_PLAZO_DE_PAGO,
  /* 23 */ a.ACTIVO                              AS ACREEDOR_ACTIVO,
  /* País del acreedor */
  /* 24 */ p.PAIS_ID                             AS PAIS_ID,
  /* 25 */ p.NOMBRE                              AS PAIS_NOMBRE,
  /* Detalles (pueden ser NULL si no hay detalles) */
  /* 26 */ df.DETALLE_FACTURA_ID                 AS DETALLE_FACTURA_ID,
  /* 27 */ df.SUBTOTAL                           AS DETALLE_SUBTOTAL,
  /* 28 */ df.DESCRIPCION                        AS DETALLE_DESCRIPCION
FROM PA_FACTURAS f
JOIN PA_MONEDAS        m  ON m.MONEDA_ID   = f.MONEDA_ID
JOIN PA_ACREEDORES     a  ON a.ACREEDOR_ID = f.ACREEDOR_ID
JOIN PA_PAISES         p  ON p.PAIS_ID     = a.PAIS_ID
LEFT JOIN PA_DETALLES_FACTURA df ON df.FACTURA_ID = f.FACTURA_ID
WHERE df.FECHA_ELIMINACION IS NULL;

-- -----------------------------------------------------
-- View `softpacbd`.`VW_PROPUESTA_COMPLETA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softpacbd`.`VW_PROPUESTA_COMPLETA`;
USE `softpacbd`;
CREATE OR REPLACE VIEW VW_PROPUESTA_COMPLETA AS
SELECT 
    -- Propuesta
    p.PROPUESTA_DE_PAGO_ID         AS P1_PROPUESTA_DE_PAGO_ID,
    p.FECHA_HORA_CREACION          AS P2_FECHA_HORA_CREACION,
    p.FECHA_HORA_MODIFICACION      AS P3_FECHA_HORA_MODIFICACION,
    p.USUARIO_CREACION             AS P4_USUARIO_CREACION,
    uc.CORREO_ELECTRONICO          AS P5_USUARIO_CREACION_CORREO,
    uc.NOMBRE_DE_USUARIO           AS P6_USUARIO_CREACION_NOMBRE_USUARIO,
    uc.NOMBRE                      AS P7_USUARIO_CREACION_NOMBRE,
    uc.APELLIDOS                   AS P8_USUARIO_CREACION_APELLIDOS,
    uc.ACTIVO                      AS P9_USUARIO_CREACION_ACTIVO,
    uc.SUPERUSUARIO                AS P10_USUARIO_CREACION_SUPERUSUARIO,
    p.USUARIO_MODIFICACION         AS P11_USUARIO_MODIFICACION,
    um.CORREO_ELECTRONICO          AS P12_USUARIO_MODIFICACION_CORREO,
    um.NOMBRE_DE_USUARIO           AS P13_USUARIO_MODIFICACION_NOMBRE_USUARIO,
    um.NOMBRE                      AS P14_USUARIO_MODIFICACION_NOMBRE,
    um.APELLIDOS                   AS P15_USUARIO_MODIFICACION_APELLIDOS,
    um.ACTIVO                      AS P16_USUARIO_MODIFICACION_ACTIVO,
    um.SUPERUSUARIO                AS P17_USUARIO_MODIFICACION_SUPERUSUARIO,
    p.ESTADO                       AS P18_ESTADO_PROPUESTA,
    p.ENTIDAD_BANCARIA_ID          AS P19_ENTIDAD_BANCARIA_PROPUESTA,
    ebp.NOMBRE                     AS P20_ENTIDAD_BANCARIA_NOMBRE,
    ebp.FORMATO_ACEPTADO           AS P21_ENTIDAD_BANCARIA_FORMATO,
    ebp.CODIGO_SWIFT               AS P22_ENTIDAD_BANCARIA_SWIFT,
    ebp.PAIS_ID                    AS P23_ENTIDAD_BANCARIA_PAIS_ID,
    pbp.NOMBRE                     AS P24_ENTIDAD_BANCARIA_PAIS_NOMBRE,
    -- Detalle de propuesta
    dp.DETALLE_PROPUESTA_ID        AS D1_DETALLE_PROPUESTA_ID,
    dp.MONTO_PAGO                  AS D2_MONTO_PAGO,
    dp.FORMA_PAGO                  AS D3_FORMA_PAGO,
    -- Factura
    f.FACTURA_ID                   AS F1_FACTURA_ID,
    f.NUMERO_FACTURA               AS F2_NUMERO_FACTURA,
    f.FECHA_EMISION                AS F3_FECHA_EMISION,
    f.FECHA_RECEPCION              AS F4_FECHA_RECEPCION,
    f.FECHA_LIMITE_PAGO            AS F5_FECHA_LIMITE_PAGO,
    f.ESTADO                       AS F6_ESTADO_FACTURA,
    f.MONTO_TOTAL                  AS F7_MONTO_TOTAL,
    f.MONTO_IGV                    AS F8_MONTO_IGV,
    f.MONTO_RESTANTE               AS F9_MONTO_RESTANTE,
    f.REGIMEN_FISCAL               AS F10_REGIMEN_FISCAL,
    f.TASA_IVA                     AS F11_TASA_IVA,
    f.OTROS_TRIBUTOS               AS F12_OTROS_TRIBUTOS,
    f.MONEDA_ID                    AS F13_MONEDA_ID,
    f.ACREEDOR_ID                  AS F14_ACREEDOR_ID,
    -- Cuenta acreedor (destino)
    ca.CUENTA_ACREEDOR_ID          AS CA1_CUENTA_ACREEDOR_ID,
    ca.TIPO_CUENTA                 AS CA2_TIPO_CUENTA,
    ca.NUMERO_CUENTA               AS CA3_NUMERO_CUENTA,
    ca.CCI                         AS CA4_CCI,
    ca.ACTIVO                      AS CA5_ACTIVO,
    ca.ACREEDOR_ID                 AS CA6_ACREEDOR_ID,
    ca.ENTIDAD_BANCARIA_ID         AS CA7_ENTIDAD_BANCARIA_ID,
    ca.MONEDA_ID                   AS CA8_MONEDA_ID,
    eba.NOMBRE                     AS CA9_ENTIDAD_BANCARIA_NOMBRE,
    eba.CODIGO_SWIFT               AS CA10_ENTIDAD_BANCARIA_SWIFT,
    eba.PAIS_ID                    AS CA11_ENTIDAD_BANCARIA_PAIS_ID,
    pba.NOMBRE                     AS CA12_ENTIDAD_BANCARIA_PAIS_NOMBRE,
    -- Cuenta propia (origen)
    cp.CUENTA_PROPIA_ID            AS CP1_CUENTA_PROPIA_ID,
    cp.SALDO_DISPONIBLE            AS CP2_SALDO_DISPONIBLE,
    cp.TIPO_CUENTA                 AS CP3_TIPO_CUENTA,
    cp.NUMERO_CUENTA               AS CP4_NUMERO_CUENTA,
    cp.CCI                         AS CP5_CCI,
    cp.ACTIVO                      AS CP6_ACTIVO,
    cp.ENTIDAD_BANCARIA_ID         AS CP7_ENTIDAD_BANCARIA_ID,
    cp.MONEDA_ID                   AS CP8_MONEDA_ID,
    ebo.NOMBRE                     AS CP9_ENTIDAD_BANCARIA_NOMBRE,
    ebo.CODIGO_SWIFT               AS CP10_ENTIDAD_BANCARIA_SWIFT,
    ebo.PAIS_ID                    AS CP11_ENTIDAD_BANCARIA_PAIS_ID,
    pbo.NOMBRE                     AS CP12_ENTIDAD_BANCARIA_PAIS_NOMBRE
FROM PA_PROPUESTAS_DE_PAGO p
JOIN PA_ENTIDADES_BANCARIAS ebp ON ebp.ENTIDAD_BANCARIA_ID = p.ENTIDAD_BANCARIA_ID
JOIN PA_PAISES pbp ON pbp.PAIS_ID = ebp.PAIS_ID
LEFT JOIN PA_USUARIOS uc ON uc.USUARIO_ID = p.USUARIO_CREACION
LEFT JOIN PA_USUARIOS um ON um.USUARIO_ID = p.USUARIO_MODIFICACION
LEFT JOIN PA_DETALLES_PROPUESTA dp ON dp.PROPUESTA_DE_PAGO_ID = p.PROPUESTA_DE_PAGO_ID
LEFT JOIN PA_FACTURAS f ON f.FACTURA_ID = dp.FACTURA_ID
LEFT JOIN PA_CUENTAS_ACREEDOR ca ON ca.CUENTA_ACREEDOR_ID = dp.CUENTA_ACREEDOR_ID
LEFT JOIN PA_ENTIDADES_BANCARIAS eba ON eba.ENTIDAD_BANCARIA_ID = ca.ENTIDAD_BANCARIA_ID
LEFT JOIN PA_PAISES pba ON pba.PAIS_ID = eba.PAIS_ID
LEFT JOIN PA_CUENTAS_PROPIAS cp ON cp.CUENTA_PROPIA_ID = dp.CUENTA_PROPIA_ID
LEFT JOIN PA_ENTIDADES_BANCARIAS ebo ON ebo.ENTIDAD_BANCARIA_ID = cp.ENTIDAD_BANCARIA_ID
LEFT JOIN PA_PAISES pbo ON pbo.PAIS_ID = ebo.PAIS_ID
WHERE dp.FECHA_ELIMINACION IS NULL;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
