-- DML Script for MSSQL
USE softpacbd;
GO

-- PA_PAISES
INSERT INTO PA_PAISES (NOMBRE, CODIGO_ISO, CODIGO_TELEFONICO) VALUES ('Perú', 'PE', '+51');
INSERT INTO PA_PAISES (NOMBRE, CODIGO_ISO, CODIGO_TELEFONICO) VALUES ('México', 'MX', '+52');
INSERT INTO PA_PAISES (NOMBRE, CODIGO_ISO, CODIGO_TELEFONICO) VALUES ('Colombia', 'CO', '+57');

-- PA_MONEDAS
INSERT INTO PA_MONEDAS (NOMBRE, CODIGO_ISO, SIMBOLO) VALUES ('Sol Peruano', 'PEN', 'S/');
INSERT INTO PA_MONEDAS (NOMBRE, CODIGO_ISO, SIMBOLO) VALUES ('Peso Mexicano', 'MXN', '$');
INSERT INTO PA_MONEDAS (NOMBRE, CODIGO_ISO, SIMBOLO) VALUES ('Peso Colombiano', 'COP', '$');
INSERT INTO PA_MONEDAS (NOMBRE, CODIGO_ISO, SIMBOLO) VALUES ('Dólar Estadounidense', 'USD', '$');

-- PA_ENTIDADES_BANCARIAS
INSERT INTO PA_ENTIDADES_BANCARIAS (NOMBRE, FORMATO_ACEPTADO, CODIGO_SWIFT, PAIS_ID) VALUES ('Banco de Crédito del Perú', 'TXT', 'BCPLPEPL', 1);
INSERT INTO PA_ENTIDADES_BANCARIAS (NOMBRE, FORMATO_ACEPTADO, CODIGO_SWIFT, PAIS_ID) VALUES ('Interbank', 'CSV', 'BINPPEPL', 1);
INSERT INTO PA_ENTIDADES_BANCARIAS (NOMBRE, FORMATO_ACEPTADO, CODIGO_SWIFT, PAIS_ID) VALUES ('BBVA Perú', 'XML', 'BCONPEPL', 1);
INSERT INTO PA_ENTIDADES_BANCARIAS (NOMBRE, FORMATO_ACEPTADO, CODIGO_SWIFT, PAIS_ID) VALUES ('Scotiabank Perú', 'MT101', 'BSUDPEPL', 1);
INSERT INTO PA_ENTIDADES_BANCARIAS (NOMBRE, FORMATO_ACEPTADO, CODIGO_SWIFT, PAIS_ID) VALUES ('BBVA México', 'TXT', 'BCMRMXMM', 2);
INSERT INTO PA_ENTIDADES_BANCARIAS (NOMBRE, FORMATO_ACEPTADO, CODIGO_SWIFT, PAIS_ID) VALUES ('Banco Santander México', 'CSV', 'BMSXMXMM', 2);
INSERT INTO PA_ENTIDADES_BANCARIAS (NOMBRE, FORMATO_ACEPTADO, CODIGO_SWIFT, PAIS_ID) VALUES ('Banorte', 'XML', 'MENOMXMT', 2);
INSERT INTO PA_ENTIDADES_BANCARIAS (NOMBRE, FORMATO_ACEPTADO, CODIGO_SWIFT, PAIS_ID) VALUES ('HSBC México', 'MT101', 'BIMEMXMM', 2);
INSERT INTO PA_ENTIDADES_BANCARIAS (NOMBRE, FORMATO_ACEPTADO, CODIGO_SWIFT, PAIS_ID) VALUES ('Bancolombia', 'TXT', 'COLOCOBM', 3);
INSERT INTO PA_ENTIDADES_BANCARIAS (NOMBRE, FORMATO_ACEPTADO, CODIGO_SWIFT, PAIS_ID) VALUES ('Banco de Bogotá', 'CSV', 'BBOPCOBM', 3);
INSERT INTO PA_ENTIDADES_BANCARIAS (NOMBRE, FORMATO_ACEPTADO, CODIGO_SWIFT, PAIS_ID) VALUES ('Davivienda', 'XML', 'CAFECOBM', 3);
INSERT INTO PA_ENTIDADES_BANCARIAS (NOMBRE, FORMATO_ACEPTADO, CODIGO_SWIFT, PAIS_ID) VALUES ('BBVA Colombia', 'MT101', 'BBVACOBM', 3);

-- PA_USUARIOS
INSERT INTO PA_USUARIOS (CORREO_ELECTRONICO, NOMBRE_DE_USUARIO, NOMBRE, APELLIDOS, ACTIVO, PASSWORD_HASH, SUPERUSUARIO) VALUES ('a20233483@pucp.edu.pe', 'DiegoAyala', 'Diego', 'Ayala de la Cruz', 'S', '$2a$10$Y2Rbizz7ddp.Fd0RP7pmN.aktufJnff/iMFs2AdAXD9tfc3bdAZgC', 'S');