//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPacBusiness.PaisesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softpacws.pucp.edu.pe/", ConfigurationName="PaisesWS.PaisesWS")]
    public interface PaisesWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/PaisesWS/obtenerPaisPorIdRequest", ReplyAction="http://softpacws.pucp.edu.pe/PaisesWS/obtenerPaisPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.PaisesWS.obtenerPaisPorIdResponse obtenerPaisPorId(SoftPacBusiness.PaisesWS.obtenerPaisPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/PaisesWS/obtenerPaisPorIdRequest", ReplyAction="http://softpacws.pucp.edu.pe/PaisesWS/obtenerPaisPorIdResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.PaisesWS.obtenerPaisPorIdResponse> obtenerPaisPorIdAsync(SoftPacBusiness.PaisesWS.obtenerPaisPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/PaisesWS/listarPaisesRequest", ReplyAction="http://softpacws.pucp.edu.pe/PaisesWS/listarPaisesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.PaisesWS.listarPaisesResponse listarPaises(SoftPacBusiness.PaisesWS.listarPaisesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/PaisesWS/listarPaisesRequest", ReplyAction="http://softpacws.pucp.edu.pe/PaisesWS/listarPaisesResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.PaisesWS.listarPaisesResponse> listarPaisesAsync(SoftPacBusiness.PaisesWS.listarPaisesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class paisesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_isoField;
        
        private string codigo_telefonicoField;
        
        private string nombreField;
        
        private int pais_idField;
        
        private bool pais_idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo_iso {
            get {
                return this.codigo_isoField;
            }
            set {
                this.codigo_isoField = value;
                this.RaisePropertyChanged("codigo_iso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo_telefonico {
            get {
                return this.codigo_telefonicoField;
            }
            set {
                this.codigo_telefonicoField = value;
                this.RaisePropertyChanged("codigo_telefonico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int pais_id {
            get {
                return this.pais_idField;
            }
            set {
                this.pais_idField = value;
                this.RaisePropertyChanged("pais_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pais_idSpecified {
            get {
                return this.pais_idFieldSpecified;
            }
            set {
                this.pais_idFieldSpecified = value;
                this.RaisePropertyChanged("pais_idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPaisPorId", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPaisPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pais_id;
        
        public obtenerPaisPorIdRequest() {
        }
        
        public obtenerPaisPorIdRequest(int pais_id) {
            this.pais_id = pais_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPaisPorIdResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPaisPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.PaisesWS.paisesDTO @return;
        
        public obtenerPaisPorIdResponse() {
        }
        
        public obtenerPaisPorIdResponse(SoftPacBusiness.PaisesWS.paisesDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPaises", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPaisesRequest {
        
        public listarPaisesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPaisesResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPaisesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.PaisesWS.paisesDTO[] @return;
        
        public listarPaisesResponse() {
        }
        
        public listarPaisesResponse(SoftPacBusiness.PaisesWS.paisesDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaisesWSChannel : SoftPacBusiness.PaisesWS.PaisesWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaisesWSClient : System.ServiceModel.ClientBase<SoftPacBusiness.PaisesWS.PaisesWS>, SoftPacBusiness.PaisesWS.PaisesWS {
        
        public PaisesWSClient() {
        }
        
        public PaisesWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaisesWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaisesWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaisesWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.PaisesWS.obtenerPaisPorIdResponse SoftPacBusiness.PaisesWS.PaisesWS.obtenerPaisPorId(SoftPacBusiness.PaisesWS.obtenerPaisPorIdRequest request) {
            return base.Channel.obtenerPaisPorId(request);
        }
        
        public SoftPacBusiness.PaisesWS.paisesDTO obtenerPaisPorId(int pais_id) {
            SoftPacBusiness.PaisesWS.obtenerPaisPorIdRequest inValue = new SoftPacBusiness.PaisesWS.obtenerPaisPorIdRequest();
            inValue.pais_id = pais_id;
            SoftPacBusiness.PaisesWS.obtenerPaisPorIdResponse retVal = ((SoftPacBusiness.PaisesWS.PaisesWS)(this)).obtenerPaisPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.PaisesWS.obtenerPaisPorIdResponse> SoftPacBusiness.PaisesWS.PaisesWS.obtenerPaisPorIdAsync(SoftPacBusiness.PaisesWS.obtenerPaisPorIdRequest request) {
            return base.Channel.obtenerPaisPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.PaisesWS.obtenerPaisPorIdResponse> obtenerPaisPorIdAsync(int pais_id) {
            SoftPacBusiness.PaisesWS.obtenerPaisPorIdRequest inValue = new SoftPacBusiness.PaisesWS.obtenerPaisPorIdRequest();
            inValue.pais_id = pais_id;
            return ((SoftPacBusiness.PaisesWS.PaisesWS)(this)).obtenerPaisPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.PaisesWS.listarPaisesResponse SoftPacBusiness.PaisesWS.PaisesWS.listarPaises(SoftPacBusiness.PaisesWS.listarPaisesRequest request) {
            return base.Channel.listarPaises(request);
        }
        
        public SoftPacBusiness.PaisesWS.paisesDTO[] listarPaises() {
            SoftPacBusiness.PaisesWS.listarPaisesRequest inValue = new SoftPacBusiness.PaisesWS.listarPaisesRequest();
            SoftPacBusiness.PaisesWS.listarPaisesResponse retVal = ((SoftPacBusiness.PaisesWS.PaisesWS)(this)).listarPaises(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.PaisesWS.listarPaisesResponse> SoftPacBusiness.PaisesWS.PaisesWS.listarPaisesAsync(SoftPacBusiness.PaisesWS.listarPaisesRequest request) {
            return base.Channel.listarPaisesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.PaisesWS.listarPaisesResponse> listarPaisesAsync() {
            SoftPacBusiness.PaisesWS.listarPaisesRequest inValue = new SoftPacBusiness.PaisesWS.listarPaisesRequest();
            return ((SoftPacBusiness.PaisesWS.PaisesWS)(this)).listarPaisesAsync(inValue);
        }
    }
}
