//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPacTest.UsuariosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", ConfigurationName="UsuariosWS.UsuariosWS")]
    public interface UsuariosWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/insertarUsuarioReq" +
            "uest", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/insertarUsuarioRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacTest.UsuariosWS.insertarUsuarioResponse insertarUsuario(SoftPacTest.UsuariosWS.insertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/insertarUsuarioReq" +
            "uest", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/insertarUsuarioRes" +
            "ponse")]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.insertarUsuarioResponse> insertarUsuarioAsync(SoftPacTest.UsuariosWS.insertarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/modificarAccesoUsu" +
            "arioRequest", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/modificarAccesoUsu" +
            "arioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacTest.UsuariosWS.modificarAccesoUsuarioResponse modificarAccesoUsuario(SoftPacTest.UsuariosWS.modificarAccesoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/modificarAccesoUsu" +
            "arioRequest", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/modificarAccesoUsu" +
            "arioResponse")]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.modificarAccesoUsuarioResponse> modificarAccesoUsuarioAsync(SoftPacTest.UsuariosWS.modificarAccesoUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/eliminarUsuarioReq" +
            "uest", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/eliminarUsuarioRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacTest.UsuariosWS.eliminarUsuarioResponse eliminarUsuario(SoftPacTest.UsuariosWS.eliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/eliminarUsuarioReq" +
            "uest", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/eliminarUsuarioRes" +
            "ponse")]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.eliminarUsuarioResponse> eliminarUsuarioAsync(SoftPacTest.UsuariosWS.eliminarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/listarUsuariosRequ" +
            "est", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/listarUsuariosResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacTest.UsuariosWS.listarUsuariosResponse listarUsuarios(SoftPacTest.UsuariosWS.listarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/listarUsuariosRequ" +
            "est", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/listarUsuariosResp" +
            "onse")]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.listarUsuariosResponse> listarUsuariosAsync(SoftPacTest.UsuariosWS.listarUsuariosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/obtenerUsuarioRequ" +
            "est", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/obtenerUsuarioResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacTest.UsuariosWS.obtenerUsuarioResponse obtenerUsuario(SoftPacTest.UsuariosWS.obtenerUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/obtenerUsuarioRequ" +
            "est", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/obtenerUsuarioResp" +
            "onse")]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.obtenerUsuarioResponse> obtenerUsuarioAsync(SoftPacTest.UsuariosWS.obtenerUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/autenticarUsuarioP" +
            "orCorreoRequest", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/autenticarUsuarioP" +
            "orCorreoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoResponse autenticarUsuarioPorCorreo(SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/autenticarUsuarioP" +
            "orCorreoRequest", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/autenticarUsuarioP" +
            "orCorreoResponse")]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoResponse> autenticarUsuarioPorCorreoAsync(SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/autenticarUsuarioP" +
            "orNombreUsuarioRequest", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/autenticarUsuarioP" +
            "orNombreUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioResponse autenticarUsuarioPorNombreUsuario(SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/autenticarUsuarioP" +
            "orNombreUsuarioRequest", ReplyAction="http://softpacws.persistance.transisoft.pucp.edu.pe/UsuariosWS/autenticarUsuarioP" +
            "orNombreUsuarioResponse")]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioResponse> autenticarUsuarioPorNombreUsuarioAsync(SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/")]
    public partial class usuariosDTO : eliminableDTOBase {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string apellidosField;
        
        private string correo_electronicoField;
        
        private string nombreField;
        
        private string nombre_de_usuarioField;
        
        private string password_hashField;
        
        private bool superusuarioField;
        
        private bool superusuarioFieldSpecified;
        
        private int usuario_idField;
        
        private bool usuario_idFieldSpecified;
        
        private usuarioPaisAccesoDTO[] usuario_paisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo_electronico {
            get {
                return this.correo_electronicoField;
            }
            set {
                this.correo_electronicoField = value;
                this.RaisePropertyChanged("correo_electronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre_de_usuario {
            get {
                return this.nombre_de_usuarioField;
            }
            set {
                this.nombre_de_usuarioField = value;
                this.RaisePropertyChanged("nombre_de_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string password_hash {
            get {
                return this.password_hashField;
            }
            set {
                this.password_hashField = value;
                this.RaisePropertyChanged("password_hash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool superusuario {
            get {
                return this.superusuarioField;
            }
            set {
                this.superusuarioField = value;
                this.RaisePropertyChanged("superusuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool superusuarioSpecified {
            get {
                return this.superusuarioFieldSpecified;
            }
            set {
                this.superusuarioFieldSpecified = value;
                this.RaisePropertyChanged("superusuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int usuario_id {
            get {
                return this.usuario_idField;
            }
            set {
                this.usuario_idField = value;
                this.RaisePropertyChanged("usuario_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuario_idSpecified {
            get {
                return this.usuario_idFieldSpecified;
            }
            set {
                this.usuario_idFieldSpecified = value;
                this.RaisePropertyChanged("usuario_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("usuario_pais", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public usuarioPaisAccesoDTO[] usuario_pais {
            get {
                return this.usuario_paisField;
            }
            set {
                this.usuario_paisField = value;
                this.RaisePropertyChanged("usuario_pais");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/")]
    public partial class usuarioPaisAccesoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool accesoField;
        
        private bool accesoFieldSpecified;
        
        private paisesDTO paisField;
        
        private usuariosDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool acceso {
            get {
                return this.accesoField;
            }
            set {
                this.accesoField = value;
                this.RaisePropertyChanged("acceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accesoSpecified {
            get {
                return this.accesoFieldSpecified;
            }
            set {
                this.accesoFieldSpecified = value;
                this.RaisePropertyChanged("accesoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public paisesDTO pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public usuariosDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/")]
    public partial class paisesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_isoField;
        
        private string codigo_telefonicoField;
        
        private string nombreField;
        
        private int pais_idField;
        
        private bool pais_idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo_iso {
            get {
                return this.codigo_isoField;
            }
            set {
                this.codigo_isoField = value;
                this.RaisePropertyChanged("codigo_iso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo_telefonico {
            get {
                return this.codigo_telefonicoField;
            }
            set {
                this.codigo_telefonicoField = value;
                this.RaisePropertyChanged("codigo_telefonico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int pais_id {
            get {
                return this.pais_idField;
            }
            set {
                this.pais_idField = value;
                this.RaisePropertyChanged("pais_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pais_idSpecified {
            get {
                return this.pais_idFieldSpecified;
            }
            set {
                this.pais_idFieldSpecified = value;
                this.RaisePropertyChanged("pais_idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuariosDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/")]
    public abstract partial class eliminableDTOBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private localDateTime fecha_eliminacionField;
        
        private usuariosDTO usuario_eliminacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDateTime fecha_eliminacion {
            get {
                return this.fecha_eliminacionField;
            }
            set {
                this.fecha_eliminacionField = value;
                this.RaisePropertyChanged("fecha_eliminacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public usuariosDTO usuario_eliminacion {
            get {
                return this.usuario_eliminacionField;
            }
            set {
                this.usuario_eliminacionField = value;
                this.RaisePropertyChanged("usuario_eliminacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuario", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacTest.UsuariosWS.usuariosDTO nuevoUsuario;
        
        public insertarUsuarioRequest() {
        }
        
        public insertarUsuarioRequest(SoftPacTest.UsuariosWS.usuariosDTO nuevoUsuario) {
            this.nuevoUsuario = nuevoUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuarioResponse", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarUsuarioResponse() {
        }
        
        public insertarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAccesoUsuario", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarAccesoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int usuarioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuevoNombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("paisesIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] paisesIds;
        
        public modificarAccesoUsuarioRequest() {
        }
        
        public modificarAccesoUsuarioRequest(int usuarioId, string nuevoNombreUsuario, bool activo, int[] paisesIds) {
            this.usuarioId = usuarioId;
            this.nuevoNombreUsuario = nuevoNombreUsuario;
            this.activo = activo;
            this.paisesIds = paisesIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAccesoUsuarioResponse", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarAccesoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarAccesoUsuarioResponse() {
        }
        
        public modificarAccesoUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarUsuario", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacTest.UsuariosWS.usuariosDTO usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacTest.UsuariosWS.usuariosDTO usuarioActual;
        
        public eliminarUsuarioRequest() {
        }
        
        public eliminarUsuarioRequest(SoftPacTest.UsuariosWS.usuariosDTO usuario, SoftPacTest.UsuariosWS.usuariosDTO usuarioActual) {
            this.usuario = usuario;
            this.usuarioActual = usuarioActual;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarUsuarioResponse", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarUsuarioResponse() {
        }
        
        public eliminarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuarios", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuariosRequest {
        
        public listarUsuariosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuariosResponse", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacTest.UsuariosWS.usuariosDTO[] @return;
        
        public listarUsuariosResponse() {
        }
        
        public listarUsuariosResponse(SoftPacTest.UsuariosWS.usuariosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerUsuario", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int usuario_id;
        
        public obtenerUsuarioRequest() {
        }
        
        public obtenerUsuarioRequest(int usuario_id) {
            this.usuario_id = usuario_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerUsuarioResponse", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacTest.UsuariosWS.usuariosDTO @return;
        
        public obtenerUsuarioResponse() {
        }
        
        public obtenerUsuarioResponse(SoftPacTest.UsuariosWS.usuariosDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticarUsuarioPorCorreo", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class autenticarUsuarioPorCorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public autenticarUsuarioPorCorreoRequest() {
        }
        
        public autenticarUsuarioPorCorreoRequest(string correo, string password) {
            this.correo = correo;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticarUsuarioPorCorreoResponse", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class autenticarUsuarioPorCorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacTest.UsuariosWS.usuariosDTO @return;
        
        public autenticarUsuarioPorCorreoResponse() {
        }
        
        public autenticarUsuarioPorCorreoResponse(SoftPacTest.UsuariosWS.usuariosDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticarUsuarioPorNombreUsuario", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class autenticarUsuarioPorNombreUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre_Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public autenticarUsuarioPorNombreUsuarioRequest() {
        }
        
        public autenticarUsuarioPorNombreUsuarioRequest(string nombre_Usuario, string password) {
            this.nombre_Usuario = nombre_Usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticarUsuarioPorNombreUsuarioResponse", WrapperNamespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class autenticarUsuarioPorNombreUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.persistance.transisoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacTest.UsuariosWS.usuariosDTO @return;
        
        public autenticarUsuarioPorNombreUsuarioResponse() {
        }
        
        public autenticarUsuarioPorNombreUsuarioResponse(SoftPacTest.UsuariosWS.usuariosDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuariosWSChannel : SoftPacTest.UsuariosWS.UsuariosWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosWSClient : System.ServiceModel.ClientBase<SoftPacTest.UsuariosWS.UsuariosWS>, SoftPacTest.UsuariosWS.UsuariosWS {
        
        public UsuariosWSClient() {
        }
        
        public UsuariosWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacTest.UsuariosWS.insertarUsuarioResponse SoftPacTest.UsuariosWS.UsuariosWS.insertarUsuario(SoftPacTest.UsuariosWS.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public int insertarUsuario(SoftPacTest.UsuariosWS.usuariosDTO nuevoUsuario) {
            SoftPacTest.UsuariosWS.insertarUsuarioRequest inValue = new SoftPacTest.UsuariosWS.insertarUsuarioRequest();
            inValue.nuevoUsuario = nuevoUsuario;
            SoftPacTest.UsuariosWS.insertarUsuarioResponse retVal = ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).insertarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.insertarUsuarioResponse> SoftPacTest.UsuariosWS.UsuariosWS.insertarUsuarioAsync(SoftPacTest.UsuariosWS.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.insertarUsuarioResponse> insertarUsuarioAsync(SoftPacTest.UsuariosWS.usuariosDTO nuevoUsuario) {
            SoftPacTest.UsuariosWS.insertarUsuarioRequest inValue = new SoftPacTest.UsuariosWS.insertarUsuarioRequest();
            inValue.nuevoUsuario = nuevoUsuario;
            return ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).insertarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacTest.UsuariosWS.modificarAccesoUsuarioResponse SoftPacTest.UsuariosWS.UsuariosWS.modificarAccesoUsuario(SoftPacTest.UsuariosWS.modificarAccesoUsuarioRequest request) {
            return base.Channel.modificarAccesoUsuario(request);
        }
        
        public int modificarAccesoUsuario(int usuarioId, string nuevoNombreUsuario, bool activo, int[] paisesIds) {
            SoftPacTest.UsuariosWS.modificarAccesoUsuarioRequest inValue = new SoftPacTest.UsuariosWS.modificarAccesoUsuarioRequest();
            inValue.usuarioId = usuarioId;
            inValue.nuevoNombreUsuario = nuevoNombreUsuario;
            inValue.activo = activo;
            inValue.paisesIds = paisesIds;
            SoftPacTest.UsuariosWS.modificarAccesoUsuarioResponse retVal = ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).modificarAccesoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.modificarAccesoUsuarioResponse> SoftPacTest.UsuariosWS.UsuariosWS.modificarAccesoUsuarioAsync(SoftPacTest.UsuariosWS.modificarAccesoUsuarioRequest request) {
            return base.Channel.modificarAccesoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.modificarAccesoUsuarioResponse> modificarAccesoUsuarioAsync(int usuarioId, string nuevoNombreUsuario, bool activo, int[] paisesIds) {
            SoftPacTest.UsuariosWS.modificarAccesoUsuarioRequest inValue = new SoftPacTest.UsuariosWS.modificarAccesoUsuarioRequest();
            inValue.usuarioId = usuarioId;
            inValue.nuevoNombreUsuario = nuevoNombreUsuario;
            inValue.activo = activo;
            inValue.paisesIds = paisesIds;
            return ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).modificarAccesoUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacTest.UsuariosWS.eliminarUsuarioResponse SoftPacTest.UsuariosWS.UsuariosWS.eliminarUsuario(SoftPacTest.UsuariosWS.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuario(request);
        }
        
        public int eliminarUsuario(SoftPacTest.UsuariosWS.usuariosDTO usuario, SoftPacTest.UsuariosWS.usuariosDTO usuarioActual) {
            SoftPacTest.UsuariosWS.eliminarUsuarioRequest inValue = new SoftPacTest.UsuariosWS.eliminarUsuarioRequest();
            inValue.usuario = usuario;
            inValue.usuarioActual = usuarioActual;
            SoftPacTest.UsuariosWS.eliminarUsuarioResponse retVal = ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).eliminarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.eliminarUsuarioResponse> SoftPacTest.UsuariosWS.UsuariosWS.eliminarUsuarioAsync(SoftPacTest.UsuariosWS.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.eliminarUsuarioResponse> eliminarUsuarioAsync(SoftPacTest.UsuariosWS.usuariosDTO usuario, SoftPacTest.UsuariosWS.usuariosDTO usuarioActual) {
            SoftPacTest.UsuariosWS.eliminarUsuarioRequest inValue = new SoftPacTest.UsuariosWS.eliminarUsuarioRequest();
            inValue.usuario = usuario;
            inValue.usuarioActual = usuarioActual;
            return ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).eliminarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacTest.UsuariosWS.listarUsuariosResponse SoftPacTest.UsuariosWS.UsuariosWS.listarUsuarios(SoftPacTest.UsuariosWS.listarUsuariosRequest request) {
            return base.Channel.listarUsuarios(request);
        }
        
        public SoftPacTest.UsuariosWS.usuariosDTO[] listarUsuarios() {
            SoftPacTest.UsuariosWS.listarUsuariosRequest inValue = new SoftPacTest.UsuariosWS.listarUsuariosRequest();
            SoftPacTest.UsuariosWS.listarUsuariosResponse retVal = ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).listarUsuarios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.listarUsuariosResponse> SoftPacTest.UsuariosWS.UsuariosWS.listarUsuariosAsync(SoftPacTest.UsuariosWS.listarUsuariosRequest request) {
            return base.Channel.listarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.listarUsuariosResponse> listarUsuariosAsync() {
            SoftPacTest.UsuariosWS.listarUsuariosRequest inValue = new SoftPacTest.UsuariosWS.listarUsuariosRequest();
            return ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).listarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacTest.UsuariosWS.obtenerUsuarioResponse SoftPacTest.UsuariosWS.UsuariosWS.obtenerUsuario(SoftPacTest.UsuariosWS.obtenerUsuarioRequest request) {
            return base.Channel.obtenerUsuario(request);
        }
        
        public SoftPacTest.UsuariosWS.usuariosDTO obtenerUsuario(int usuario_id) {
            SoftPacTest.UsuariosWS.obtenerUsuarioRequest inValue = new SoftPacTest.UsuariosWS.obtenerUsuarioRequest();
            inValue.usuario_id = usuario_id;
            SoftPacTest.UsuariosWS.obtenerUsuarioResponse retVal = ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).obtenerUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.obtenerUsuarioResponse> SoftPacTest.UsuariosWS.UsuariosWS.obtenerUsuarioAsync(SoftPacTest.UsuariosWS.obtenerUsuarioRequest request) {
            return base.Channel.obtenerUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.obtenerUsuarioResponse> obtenerUsuarioAsync(int usuario_id) {
            SoftPacTest.UsuariosWS.obtenerUsuarioRequest inValue = new SoftPacTest.UsuariosWS.obtenerUsuarioRequest();
            inValue.usuario_id = usuario_id;
            return ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).obtenerUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoResponse SoftPacTest.UsuariosWS.UsuariosWS.autenticarUsuarioPorCorreo(SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoRequest request) {
            return base.Channel.autenticarUsuarioPorCorreo(request);
        }
        
        public SoftPacTest.UsuariosWS.usuariosDTO autenticarUsuarioPorCorreo(string correo, string password) {
            SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoRequest inValue = new SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoRequest();
            inValue.correo = correo;
            inValue.password = password;
            SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoResponse retVal = ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).autenticarUsuarioPorCorreo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoResponse> SoftPacTest.UsuariosWS.UsuariosWS.autenticarUsuarioPorCorreoAsync(SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoRequest request) {
            return base.Channel.autenticarUsuarioPorCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoResponse> autenticarUsuarioPorCorreoAsync(string correo, string password) {
            SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoRequest inValue = new SoftPacTest.UsuariosWS.autenticarUsuarioPorCorreoRequest();
            inValue.correo = correo;
            inValue.password = password;
            return ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).autenticarUsuarioPorCorreoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioResponse SoftPacTest.UsuariosWS.UsuariosWS.autenticarUsuarioPorNombreUsuario(SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioRequest request) {
            return base.Channel.autenticarUsuarioPorNombreUsuario(request);
        }
        
        public SoftPacTest.UsuariosWS.usuariosDTO autenticarUsuarioPorNombreUsuario(string nombre_Usuario, string password) {
            SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioRequest inValue = new SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioRequest();
            inValue.nombre_Usuario = nombre_Usuario;
            inValue.password = password;
            SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioResponse retVal = ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).autenticarUsuarioPorNombreUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioResponse> SoftPacTest.UsuariosWS.UsuariosWS.autenticarUsuarioPorNombreUsuarioAsync(SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioRequest request) {
            return base.Channel.autenticarUsuarioPorNombreUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioResponse> autenticarUsuarioPorNombreUsuarioAsync(string nombre_Usuario, string password) {
            SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioRequest inValue = new SoftPacTest.UsuariosWS.autenticarUsuarioPorNombreUsuarioRequest();
            inValue.nombre_Usuario = nombre_Usuario;
            inValue.password = password;
            return ((SoftPacTest.UsuariosWS.UsuariosWS)(this)).autenticarUsuarioPorNombreUsuarioAsync(inValue);
        }
    }
}
