//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPacBusiness.MonedasWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softpacws.pucp.edu.pe/", ConfigurationName="MonedasWS.MonedasWS")]
    public interface MonedasWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/MonedasWS/obtenerMonedaPorDivisaRequest", ReplyAction="http://softpacws.pucp.edu.pe/MonedasWS/obtenerMonedaPorDivisaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaResponse obtenerMonedaPorDivisa(SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/MonedasWS/obtenerMonedaPorDivisaRequest", ReplyAction="http://softpacws.pucp.edu.pe/MonedasWS/obtenerMonedaPorDivisaResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaResponse> obtenerMonedaPorDivisaAsync(SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/MonedasWS/obtenerMonedaPorIDRequest", ReplyAction="http://softpacws.pucp.edu.pe/MonedasWS/obtenerMonedaPorIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.MonedasWS.obtenerMonedaPorIDResponse obtenerMonedaPorID(SoftPacBusiness.MonedasWS.obtenerMonedaPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/MonedasWS/obtenerMonedaPorIDRequest", ReplyAction="http://softpacws.pucp.edu.pe/MonedasWS/obtenerMonedaPorIDResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.MonedasWS.obtenerMonedaPorIDResponse> obtenerMonedaPorIDAsync(SoftPacBusiness.MonedasWS.obtenerMonedaPorIDRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/MonedasWS/listarMonedasRequest", ReplyAction="http://softpacws.pucp.edu.pe/MonedasWS/listarMonedasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.MonedasWS.listarMonedasResponse listarMonedas(SoftPacBusiness.MonedasWS.listarMonedasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/MonedasWS/listarMonedasRequest", ReplyAction="http://softpacws.pucp.edu.pe/MonedasWS/listarMonedasResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.MonedasWS.listarMonedasResponse> listarMonedasAsync(SoftPacBusiness.MonedasWS.listarMonedasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class monedasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_isoField;
        
        private int moneda_idField;
        
        private bool moneda_idFieldSpecified;
        
        private string nombreField;
        
        private string simboloField;
        
        private tiposDeCambioDTO[] tipos_cambioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo_iso {
            get {
                return this.codigo_isoField;
            }
            set {
                this.codigo_isoField = value;
                this.RaisePropertyChanged("codigo_iso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int moneda_id {
            get {
                return this.moneda_idField;
            }
            set {
                this.moneda_idField = value;
                this.RaisePropertyChanged("moneda_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moneda_idSpecified {
            get {
                return this.moneda_idFieldSpecified;
            }
            set {
                this.moneda_idFieldSpecified = value;
                this.RaisePropertyChanged("moneda_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string simbolo {
            get {
                return this.simboloField;
            }
            set {
                this.simboloField = value;
                this.RaisePropertyChanged("simbolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipos_cambio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public tiposDeCambioDTO[] tipos_cambio {
            get {
                return this.tipos_cambioField;
            }
            set {
                this.tipos_cambioField = value;
                this.RaisePropertyChanged("tipos_cambio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class tiposDeCambioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private monedasDTO moneda_destinoField;
        
        private monedasDTO moneda_origenField;
        
        private decimal tasa_de_cambioField;
        
        private bool tasa_de_cambioFieldSpecified;
        
        private int tipo_cambio_idField;
        
        private bool tipo_cambio_idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public monedasDTO moneda_destino {
            get {
                return this.moneda_destinoField;
            }
            set {
                this.moneda_destinoField = value;
                this.RaisePropertyChanged("moneda_destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public monedasDTO moneda_origen {
            get {
                return this.moneda_origenField;
            }
            set {
                this.moneda_origenField = value;
                this.RaisePropertyChanged("moneda_origen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal tasa_de_cambio {
            get {
                return this.tasa_de_cambioField;
            }
            set {
                this.tasa_de_cambioField = value;
                this.RaisePropertyChanged("tasa_de_cambio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tasa_de_cambioSpecified {
            get {
                return this.tasa_de_cambioFieldSpecified;
            }
            set {
                this.tasa_de_cambioFieldSpecified = value;
                this.RaisePropertyChanged("tasa_de_cambioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int tipo_cambio_id {
            get {
                return this.tipo_cambio_idField;
            }
            set {
                this.tipo_cambio_idField = value;
                this.RaisePropertyChanged("tipo_cambio_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipo_cambio_idSpecified {
            get {
                return this.tipo_cambio_idFieldSpecified;
            }
            set {
                this.tipo_cambio_idFieldSpecified = value;
                this.RaisePropertyChanged("tipo_cambio_idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMonedaPorDivisa", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerMonedaPorDivisaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string moneda_divisa;
        
        public obtenerMonedaPorDivisaRequest() {
        }
        
        public obtenerMonedaPorDivisaRequest(string moneda_divisa) {
            this.moneda_divisa = moneda_divisa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMonedaPorDivisaResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerMonedaPorDivisaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.MonedasWS.monedasDTO @return;
        
        public obtenerMonedaPorDivisaResponse() {
        }
        
        public obtenerMonedaPorDivisaResponse(SoftPacBusiness.MonedasWS.monedasDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMonedaPorID", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerMonedaPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int moneda_id;
        
        public obtenerMonedaPorIDRequest() {
        }
        
        public obtenerMonedaPorIDRequest(int moneda_id) {
            this.moneda_id = moneda_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMonedaPorIDResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerMonedaPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.MonedasWS.monedasDTO @return;
        
        public obtenerMonedaPorIDResponse() {
        }
        
        public obtenerMonedaPorIDResponse(SoftPacBusiness.MonedasWS.monedasDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMonedas", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarMonedasRequest {
        
        public listarMonedasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMonedasResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarMonedasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.MonedasWS.monedasDTO[] @return;
        
        public listarMonedasResponse() {
        }
        
        public listarMonedasResponse(SoftPacBusiness.MonedasWS.monedasDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MonedasWSChannel : SoftPacBusiness.MonedasWS.MonedasWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonedasWSClient : System.ServiceModel.ClientBase<SoftPacBusiness.MonedasWS.MonedasWS>, SoftPacBusiness.MonedasWS.MonedasWS {
        
        public MonedasWSClient() {
        }
        
        public MonedasWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonedasWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonedasWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonedasWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaResponse SoftPacBusiness.MonedasWS.MonedasWS.obtenerMonedaPorDivisa(SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaRequest request) {
            return base.Channel.obtenerMonedaPorDivisa(request);
        }
        
        public SoftPacBusiness.MonedasWS.monedasDTO obtenerMonedaPorDivisa(string moneda_divisa) {
            SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaRequest inValue = new SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaRequest();
            inValue.moneda_divisa = moneda_divisa;
            SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaResponse retVal = ((SoftPacBusiness.MonedasWS.MonedasWS)(this)).obtenerMonedaPorDivisa(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaResponse> SoftPacBusiness.MonedasWS.MonedasWS.obtenerMonedaPorDivisaAsync(SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaRequest request) {
            return base.Channel.obtenerMonedaPorDivisaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaResponse> obtenerMonedaPorDivisaAsync(string moneda_divisa) {
            SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaRequest inValue = new SoftPacBusiness.MonedasWS.obtenerMonedaPorDivisaRequest();
            inValue.moneda_divisa = moneda_divisa;
            return ((SoftPacBusiness.MonedasWS.MonedasWS)(this)).obtenerMonedaPorDivisaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.MonedasWS.obtenerMonedaPorIDResponse SoftPacBusiness.MonedasWS.MonedasWS.obtenerMonedaPorID(SoftPacBusiness.MonedasWS.obtenerMonedaPorIDRequest request) {
            return base.Channel.obtenerMonedaPorID(request);
        }
        
        public SoftPacBusiness.MonedasWS.monedasDTO obtenerMonedaPorID(int moneda_id) {
            SoftPacBusiness.MonedasWS.obtenerMonedaPorIDRequest inValue = new SoftPacBusiness.MonedasWS.obtenerMonedaPorIDRequest();
            inValue.moneda_id = moneda_id;
            SoftPacBusiness.MonedasWS.obtenerMonedaPorIDResponse retVal = ((SoftPacBusiness.MonedasWS.MonedasWS)(this)).obtenerMonedaPorID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.MonedasWS.obtenerMonedaPorIDResponse> SoftPacBusiness.MonedasWS.MonedasWS.obtenerMonedaPorIDAsync(SoftPacBusiness.MonedasWS.obtenerMonedaPorIDRequest request) {
            return base.Channel.obtenerMonedaPorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.MonedasWS.obtenerMonedaPorIDResponse> obtenerMonedaPorIDAsync(int moneda_id) {
            SoftPacBusiness.MonedasWS.obtenerMonedaPorIDRequest inValue = new SoftPacBusiness.MonedasWS.obtenerMonedaPorIDRequest();
            inValue.moneda_id = moneda_id;
            return ((SoftPacBusiness.MonedasWS.MonedasWS)(this)).obtenerMonedaPorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.MonedasWS.listarMonedasResponse SoftPacBusiness.MonedasWS.MonedasWS.listarMonedas(SoftPacBusiness.MonedasWS.listarMonedasRequest request) {
            return base.Channel.listarMonedas(request);
        }
        
        public SoftPacBusiness.MonedasWS.monedasDTO[] listarMonedas() {
            SoftPacBusiness.MonedasWS.listarMonedasRequest inValue = new SoftPacBusiness.MonedasWS.listarMonedasRequest();
            SoftPacBusiness.MonedasWS.listarMonedasResponse retVal = ((SoftPacBusiness.MonedasWS.MonedasWS)(this)).listarMonedas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.MonedasWS.listarMonedasResponse> SoftPacBusiness.MonedasWS.MonedasWS.listarMonedasAsync(SoftPacBusiness.MonedasWS.listarMonedasRequest request) {
            return base.Channel.listarMonedasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.MonedasWS.listarMonedasResponse> listarMonedasAsync() {
            SoftPacBusiness.MonedasWS.listarMonedasRequest inValue = new SoftPacBusiness.MonedasWS.listarMonedasRequest();
            return ((SoftPacBusiness.MonedasWS.MonedasWS)(this)).listarMonedasAsync(inValue);
        }
    }
}
