//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPacBusiness.EntidadesBancariasWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softpacws.pucp.edu.pe/", ConfigurationName="EntidadesBancariasWS.EntidadesBancariasWS")]
    public interface EntidadesBancariasWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/EntidadesBancariasWS/obtenerEntidadBancariaPorIdRequ" +
            "est", ReplyAction="http://softpacws.pucp.edu.pe/EntidadesBancariasWS/obtenerEntidadBancariaPorIdResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdResponse obtenerEntidadBancariaPorId(SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/EntidadesBancariasWS/obtenerEntidadBancariaPorIdRequ" +
            "est", ReplyAction="http://softpacws.pucp.edu.pe/EntidadesBancariasWS/obtenerEntidadBancariaPorIdResp" +
            "onse")]
        System.Threading.Tasks.Task<SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdResponse> obtenerEntidadBancariaPorIdAsync(SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/EntidadesBancariasWS/listarEntidadesBancariasRequest" +
            "", ReplyAction="http://softpacws.pucp.edu.pe/EntidadesBancariasWS/listarEntidadesBancariasRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasResponse listarEntidadesBancarias(SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/EntidadesBancariasWS/listarEntidadesBancariasRequest" +
            "", ReplyAction="http://softpacws.pucp.edu.pe/EntidadesBancariasWS/listarEntidadesBancariasRespons" +
            "e")]
        System.Threading.Tasks.Task<SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasResponse> listarEntidadesBancariasAsync(SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class entidadesBancariasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_swiftField;
        
        private int entidad_bancaria_idField;
        
        private bool entidad_bancaria_idFieldSpecified;
        
        private string formato_aceptadoField;
        
        private string nombreField;
        
        private paisesDTO paisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo_swift {
            get {
                return this.codigo_swiftField;
            }
            set {
                this.codigo_swiftField = value;
                this.RaisePropertyChanged("codigo_swift");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int entidad_bancaria_id {
            get {
                return this.entidad_bancaria_idField;
            }
            set {
                this.entidad_bancaria_idField = value;
                this.RaisePropertyChanged("entidad_bancaria_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entidad_bancaria_idSpecified {
            get {
                return this.entidad_bancaria_idFieldSpecified;
            }
            set {
                this.entidad_bancaria_idFieldSpecified = value;
                this.RaisePropertyChanged("entidad_bancaria_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string formato_aceptado {
            get {
                return this.formato_aceptadoField;
            }
            set {
                this.formato_aceptadoField = value;
                this.RaisePropertyChanged("formato_aceptado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public paisesDTO pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class paisesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_isoField;
        
        private string codigo_telefonicoField;
        
        private string nombreField;
        
        private int pais_idField;
        
        private bool pais_idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo_iso {
            get {
                return this.codigo_isoField;
            }
            set {
                this.codigo_isoField = value;
                this.RaisePropertyChanged("codigo_iso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo_telefonico {
            get {
                return this.codigo_telefonicoField;
            }
            set {
                this.codigo_telefonicoField = value;
                this.RaisePropertyChanged("codigo_telefonico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int pais_id {
            get {
                return this.pais_idField;
            }
            set {
                this.pais_idField = value;
                this.RaisePropertyChanged("pais_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pais_idSpecified {
            get {
                return this.pais_idFieldSpecified;
            }
            set {
                this.pais_idFieldSpecified = value;
                this.RaisePropertyChanged("pais_idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEntidadBancariaPorId", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEntidadBancariaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entidades_bancarias_id;
        
        public obtenerEntidadBancariaPorIdRequest() {
        }
        
        public obtenerEntidadBancariaPorIdRequest(int entidades_bancarias_id) {
            this.entidades_bancarias_id = entidades_bancarias_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEntidadBancariaPorIdResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEntidadBancariaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.EntidadesBancariasWS.entidadesBancariasDTO @return;
        
        public obtenerEntidadBancariaPorIdResponse() {
        }
        
        public obtenerEntidadBancariaPorIdResponse(SoftPacBusiness.EntidadesBancariasWS.entidadesBancariasDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEntidadesBancarias", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEntidadesBancariasRequest {
        
        public listarEntidadesBancariasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEntidadesBancariasResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEntidadesBancariasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.EntidadesBancariasWS.entidadesBancariasDTO[] @return;
        
        public listarEntidadesBancariasResponse() {
        }
        
        public listarEntidadesBancariasResponse(SoftPacBusiness.EntidadesBancariasWS.entidadesBancariasDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EntidadesBancariasWSChannel : SoftPacBusiness.EntidadesBancariasWS.EntidadesBancariasWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntidadesBancariasWSClient : System.ServiceModel.ClientBase<SoftPacBusiness.EntidadesBancariasWS.EntidadesBancariasWS>, SoftPacBusiness.EntidadesBancariasWS.EntidadesBancariasWS {
        
        public EntidadesBancariasWSClient() {
        }
        
        public EntidadesBancariasWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntidadesBancariasWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntidadesBancariasWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntidadesBancariasWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdResponse SoftPacBusiness.EntidadesBancariasWS.EntidadesBancariasWS.obtenerEntidadBancariaPorId(SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdRequest request) {
            return base.Channel.obtenerEntidadBancariaPorId(request);
        }
        
        public SoftPacBusiness.EntidadesBancariasWS.entidadesBancariasDTO obtenerEntidadBancariaPorId(int entidades_bancarias_id) {
            SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdRequest inValue = new SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdRequest();
            inValue.entidades_bancarias_id = entidades_bancarias_id;
            SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdResponse retVal = ((SoftPacBusiness.EntidadesBancariasWS.EntidadesBancariasWS)(this)).obtenerEntidadBancariaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdResponse> SoftPacBusiness.EntidadesBancariasWS.EntidadesBancariasWS.obtenerEntidadBancariaPorIdAsync(SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdRequest request) {
            return base.Channel.obtenerEntidadBancariaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdResponse> obtenerEntidadBancariaPorIdAsync(int entidades_bancarias_id) {
            SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdRequest inValue = new SoftPacBusiness.EntidadesBancariasWS.obtenerEntidadBancariaPorIdRequest();
            inValue.entidades_bancarias_id = entidades_bancarias_id;
            return ((SoftPacBusiness.EntidadesBancariasWS.EntidadesBancariasWS)(this)).obtenerEntidadBancariaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasResponse SoftPacBusiness.EntidadesBancariasWS.EntidadesBancariasWS.listarEntidadesBancarias(SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasRequest request) {
            return base.Channel.listarEntidadesBancarias(request);
        }
        
        public SoftPacBusiness.EntidadesBancariasWS.entidadesBancariasDTO[] listarEntidadesBancarias() {
            SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasRequest inValue = new SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasRequest();
            SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasResponse retVal = ((SoftPacBusiness.EntidadesBancariasWS.EntidadesBancariasWS)(this)).listarEntidadesBancarias(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasResponse> SoftPacBusiness.EntidadesBancariasWS.EntidadesBancariasWS.listarEntidadesBancariasAsync(SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasRequest request) {
            return base.Channel.listarEntidadesBancariasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasResponse> listarEntidadesBancariasAsync() {
            SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasRequest inValue = new SoftPacBusiness.EntidadesBancariasWS.listarEntidadesBancariasRequest();
            return ((SoftPacBusiness.EntidadesBancariasWS.EntidadesBancariasWS)(this)).listarEntidadesBancariasAsync(inValue);
        }
    }
}
