//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPacWA
{


    public partial class NuevaFactura
    {

        /// <summary>
        /// Control upNuevaFactura.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upNuevaFactura;

        /// <summary>
        /// Control vsNuevaFactura.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary vsNuevaFactura;

        /// <summary>
        /// Control txtNumeroFactura.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNumeroFactura;

        /// <summary>
        /// Control ddlProveedor.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlProveedor;

        /// <summary>
        /// Control ddlMoneda.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlMoneda;

        /// <summary>
        /// Control ddlEstado.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        /// <summary>
        /// Control txtFechaEmision.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFechaEmision;

        /// <summary>
        /// Control txtFechaRecepcion.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFechaRecepcion;

        /// <summary>
        /// Control txtFechaLimitePago.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFechaLimitePago;

        /// <summary>
        /// Control txtRegimenFiscal.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtRegimenFiscal;

        /// <summary>
        /// Control txtTasaIva.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtTasaIva;

        /// <summary>
        /// Control txtOtrosTributos.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtOtrosTributos;

        /// <summary>
        /// Control txtDescripcionDetalle.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDescripcionDetalle;

        /// <summary>
        /// Control txtSubtotalDetalle.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSubtotalDetalle;

        /// <summary>
        /// Control btnAgregarDetalle.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnAgregarDetalle;

        /// <summary>
        /// Control gvDetalles.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvDetalles;

        /// <summary>
        /// Control lblSubtotal.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSubtotal;

        /// <summary>
        /// Control lblIgv.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblIgv;

        /// <summary>
        /// Control lblTotal.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotal;

        /// <summary>
        /// Control btnGuardar.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>
        /// Control btnCancelar.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnCancelar;

        /// <summary>
        /// Control hfFacturaId.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Modifique la declaración del campo en el archivo del diseñador asociado si es necesario.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfFacturaId;
    }
}
