//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPacBusiness.FacturasWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softpacws.pucp.edu.pe/", ConfigurationName="FacturasWS.FacturasWS")]
    public interface FacturasWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/listarPendientesPorCriteriosRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/listarPendientesPorCriteriosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosResponse listarPendientesPorCriterios(SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/listarPendientesPorCriteriosRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/listarPendientesPorCriteriosResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosResponse> listarPendientesPorCriteriosAsync(SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/listarFacturasRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/listarFacturasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.FacturasWS.listarFacturasResponse listarFacturas(SoftPacBusiness.FacturasWS.listarFacturasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/listarFacturasRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/listarFacturasResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.listarFacturasResponse> listarFacturasAsync(SoftPacBusiness.FacturasWS.listarFacturasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/modificarFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/modificarFacturaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.FacturasWS.modificarFacturaResponse modificarFactura(SoftPacBusiness.FacturasWS.modificarFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/modificarFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/modificarFacturaResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.modificarFacturaResponse> modificarFacturaAsync(SoftPacBusiness.FacturasWS.modificarFacturaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/listarPendientesRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/listarPendientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.FacturasWS.listarPendientesResponse listarPendientes(SoftPacBusiness.FacturasWS.listarPendientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/listarPendientesRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/listarPendientesResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.listarPendientesResponse> listarPendientesAsync(SoftPacBusiness.FacturasWS.listarPendientesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/obtenerFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/obtenerFacturaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.FacturasWS.obtenerFacturaResponse obtenerFactura(SoftPacBusiness.FacturasWS.obtenerFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/obtenerFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/obtenerFacturaResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.obtenerFacturaResponse> obtenerFacturaAsync(SoftPacBusiness.FacturasWS.obtenerFacturaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/insertarFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/insertarFacturaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.FacturasWS.insertarFacturaResponse insertarFactura(SoftPacBusiness.FacturasWS.insertarFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/insertarFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/insertarFacturaResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.insertarFacturaResponse> insertarFacturaAsync(SoftPacBusiness.FacturasWS.insertarFacturaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/eliminarFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/eliminarFacturaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.FacturasWS.eliminarFacturaResponse eliminarFactura(SoftPacBusiness.FacturasWS.eliminarFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/eliminarFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/eliminarFacturaResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.eliminarFacturaResponse> eliminarFacturaAsync(SoftPacBusiness.FacturasWS.eliminarFacturaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/insertarDetalleFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/insertarDetalleFacturaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.FacturasWS.insertarDetalleFacturaResponse insertarDetalleFactura(SoftPacBusiness.FacturasWS.insertarDetalleFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/insertarDetalleFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/insertarDetalleFacturaResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.insertarDetalleFacturaResponse> insertarDetalleFacturaAsync(SoftPacBusiness.FacturasWS.insertarDetalleFacturaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/modificarDetalleFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/modificarDetalleFacturaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.FacturasWS.modificarDetalleFacturaResponse modificarDetalleFactura(SoftPacBusiness.FacturasWS.modificarDetalleFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/modificarDetalleFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/modificarDetalleFacturaResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.modificarDetalleFacturaResponse> modificarDetalleFacturaAsync(SoftPacBusiness.FacturasWS.modificarDetalleFacturaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/eliminarDetalleFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/eliminarDetalleFacturaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eliminableDTOBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPacBusiness.FacturasWS.eliminarDetalleFacturaResponse eliminarDetalleFactura(SoftPacBusiness.FacturasWS.eliminarDetalleFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softpacws.pucp.edu.pe/FacturasWS/eliminarDetalleFacturaRequest", ReplyAction="http://softpacws.pucp.edu.pe/FacturasWS/eliminarDetalleFacturaResponse")]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.eliminarDetalleFacturaResponse> eliminarDetalleFacturaAsync(SoftPacBusiness.FacturasWS.eliminarDetalleFacturaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class facturasDTO : eliminableDTOBase {
        
        private acreedoresDTO acreedorField;
        
        private detallesFacturaDTO[] detalles_FacturaField;
        
        private string estadoField;
        
        private int factura_idField;
        
        private bool factura_idFieldSpecified;
        
        private System.DateTime fecha_emisionField;
        
        private bool fecha_emisionFieldSpecified;
        
        private System.DateTime fecha_limite_pagoField;
        
        private bool fecha_limite_pagoFieldSpecified;
        
        private System.DateTime fecha_recepcionField;
        
        private bool fecha_recepcionFieldSpecified;
        
        private monedasDTO monedaField;
        
        private decimal monto_igvField;
        
        private bool monto_igvFieldSpecified;
        
        private decimal monto_restanteField;
        
        private bool monto_restanteFieldSpecified;
        
        private decimal monto_totalField;
        
        private bool monto_totalFieldSpecified;
        
        private string numero_facturaField;
        
        private decimal otros_tributosField;
        
        private bool otros_tributosFieldSpecified;
        
        private string regimen_fiscalField;
        
        private decimal tasa_ivaField;
        
        private bool tasa_ivaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public acreedoresDTO acreedor {
            get {
                return this.acreedorField;
            }
            set {
                this.acreedorField = value;
                this.RaisePropertyChanged("acreedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detalles_Factura", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public detallesFacturaDTO[] detalles_Factura {
            get {
                return this.detalles_FacturaField;
            }
            set {
                this.detalles_FacturaField = value;
                this.RaisePropertyChanged("detalles_Factura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int factura_id {
            get {
                return this.factura_idField;
            }
            set {
                this.factura_idField = value;
                this.RaisePropertyChanged("factura_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool factura_idSpecified {
            get {
                return this.factura_idFieldSpecified;
            }
            set {
                this.factura_idFieldSpecified = value;
                this.RaisePropertyChanged("factura_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fecha_emision {
            get {
                return this.fecha_emisionField;
            }
            set {
                this.fecha_emisionField = value;
                this.RaisePropertyChanged("fecha_emision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_emisionSpecified {
            get {
                return this.fecha_emisionFieldSpecified;
            }
            set {
                this.fecha_emisionFieldSpecified = value;
                this.RaisePropertyChanged("fecha_emisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fecha_limite_pago {
            get {
                return this.fecha_limite_pagoField;
            }
            set {
                this.fecha_limite_pagoField = value;
                this.RaisePropertyChanged("fecha_limite_pago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_limite_pagoSpecified {
            get {
                return this.fecha_limite_pagoFieldSpecified;
            }
            set {
                this.fecha_limite_pagoFieldSpecified = value;
                this.RaisePropertyChanged("fecha_limite_pagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fecha_recepcion {
            get {
                return this.fecha_recepcionField;
            }
            set {
                this.fecha_recepcionField = value;
                this.RaisePropertyChanged("fecha_recepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_recepcionSpecified {
            get {
                return this.fecha_recepcionFieldSpecified;
            }
            set {
                this.fecha_recepcionFieldSpecified = value;
                this.RaisePropertyChanged("fecha_recepcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public monedasDTO moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal monto_igv {
            get {
                return this.monto_igvField;
            }
            set {
                this.monto_igvField = value;
                this.RaisePropertyChanged("monto_igv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monto_igvSpecified {
            get {
                return this.monto_igvFieldSpecified;
            }
            set {
                this.monto_igvFieldSpecified = value;
                this.RaisePropertyChanged("monto_igvSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal monto_restante {
            get {
                return this.monto_restanteField;
            }
            set {
                this.monto_restanteField = value;
                this.RaisePropertyChanged("monto_restante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monto_restanteSpecified {
            get {
                return this.monto_restanteFieldSpecified;
            }
            set {
                this.monto_restanteFieldSpecified = value;
                this.RaisePropertyChanged("monto_restanteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal monto_total {
            get {
                return this.monto_totalField;
            }
            set {
                this.monto_totalField = value;
                this.RaisePropertyChanged("monto_total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monto_totalSpecified {
            get {
                return this.monto_totalFieldSpecified;
            }
            set {
                this.monto_totalFieldSpecified = value;
                this.RaisePropertyChanged("monto_totalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string numero_factura {
            get {
                return this.numero_facturaField;
            }
            set {
                this.numero_facturaField = value;
                this.RaisePropertyChanged("numero_factura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal otros_tributos {
            get {
                return this.otros_tributosField;
            }
            set {
                this.otros_tributosField = value;
                this.RaisePropertyChanged("otros_tributos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool otros_tributosSpecified {
            get {
                return this.otros_tributosFieldSpecified;
            }
            set {
                this.otros_tributosFieldSpecified = value;
                this.RaisePropertyChanged("otros_tributosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string regimen_fiscal {
            get {
                return this.regimen_fiscalField;
            }
            set {
                this.regimen_fiscalField = value;
                this.RaisePropertyChanged("regimen_fiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal tasa_iva {
            get {
                return this.tasa_ivaField;
            }
            set {
                this.tasa_ivaField = value;
                this.RaisePropertyChanged("tasa_iva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tasa_ivaSpecified {
            get {
                return this.tasa_ivaFieldSpecified;
            }
            set {
                this.tasa_ivaFieldSpecified = value;
                this.RaisePropertyChanged("tasa_ivaSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class acreedoresDTO : eliminableDTOBase {
        
        private int acreedor_idField;
        
        private bool acreedor_idFieldSpecified;
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string condicionField;
        
        private string direccion_fiscalField;
        
        private paisesDTO paisField;
        
        private int plazo_de_pagoField;
        
        private bool plazo_de_pagoFieldSpecified;
        
        private string razon_socialField;
        
        private string rucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int acreedor_id {
            get {
                return this.acreedor_idField;
            }
            set {
                this.acreedor_idField = value;
                this.RaisePropertyChanged("acreedor_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acreedor_idSpecified {
            get {
                return this.acreedor_idFieldSpecified;
            }
            set {
                this.acreedor_idFieldSpecified = value;
                this.RaisePropertyChanged("acreedor_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string condicion {
            get {
                return this.condicionField;
            }
            set {
                this.condicionField = value;
                this.RaisePropertyChanged("condicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccion_fiscal {
            get {
                return this.direccion_fiscalField;
            }
            set {
                this.direccion_fiscalField = value;
                this.RaisePropertyChanged("direccion_fiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public paisesDTO pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int plazo_de_pago {
            get {
                return this.plazo_de_pagoField;
            }
            set {
                this.plazo_de_pagoField = value;
                this.RaisePropertyChanged("plazo_de_pago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plazo_de_pagoSpecified {
            get {
                return this.plazo_de_pagoFieldSpecified;
            }
            set {
                this.plazo_de_pagoFieldSpecified = value;
                this.RaisePropertyChanged("plazo_de_pagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string razon_social {
            get {
                return this.razon_socialField;
            }
            set {
                this.razon_socialField = value;
                this.RaisePropertyChanged("razon_social");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class paisesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_isoField;
        
        private string codigo_telefonicoField;
        
        private string nombreField;
        
        private int pais_idField;
        
        private bool pais_idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo_iso {
            get {
                return this.codigo_isoField;
            }
            set {
                this.codigo_isoField = value;
                this.RaisePropertyChanged("codigo_iso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo_telefonico {
            get {
                return this.codigo_telefonicoField;
            }
            set {
                this.codigo_telefonicoField = value;
                this.RaisePropertyChanged("codigo_telefonico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int pais_id {
            get {
                return this.pais_idField;
            }
            set {
                this.pais_idField = value;
                this.RaisePropertyChanged("pais_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pais_idSpecified {
            get {
                return this.pais_idFieldSpecified;
            }
            set {
                this.pais_idFieldSpecified = value;
                this.RaisePropertyChanged("pais_idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class tiposDeCambioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private monedasDTO moneda_destinoField;
        
        private monedasDTO moneda_origenField;
        
        private decimal tasa_de_cambioField;
        
        private bool tasa_de_cambioFieldSpecified;
        
        private int tipo_cambio_idField;
        
        private bool tipo_cambio_idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public monedasDTO moneda_destino {
            get {
                return this.moneda_destinoField;
            }
            set {
                this.moneda_destinoField = value;
                this.RaisePropertyChanged("moneda_destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public monedasDTO moneda_origen {
            get {
                return this.moneda_origenField;
            }
            set {
                this.moneda_origenField = value;
                this.RaisePropertyChanged("moneda_origen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal tasa_de_cambio {
            get {
                return this.tasa_de_cambioField;
            }
            set {
                this.tasa_de_cambioField = value;
                this.RaisePropertyChanged("tasa_de_cambio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tasa_de_cambioSpecified {
            get {
                return this.tasa_de_cambioFieldSpecified;
            }
            set {
                this.tasa_de_cambioFieldSpecified = value;
                this.RaisePropertyChanged("tasa_de_cambioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int tipo_cambio_id {
            get {
                return this.tipo_cambio_idField;
            }
            set {
                this.tipo_cambio_idField = value;
                this.RaisePropertyChanged("tipo_cambio_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipo_cambio_idSpecified {
            get {
                return this.tipo_cambio_idFieldSpecified;
            }
            set {
                this.tipo_cambio_idFieldSpecified = value;
                this.RaisePropertyChanged("tipo_cambio_idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class monedasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_isoField;
        
        private int moneda_idField;
        
        private bool moneda_idFieldSpecified;
        
        private string nombreField;
        
        private string simboloField;
        
        private tiposDeCambioDTO[] tipos_cambioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo_iso {
            get {
                return this.codigo_isoField;
            }
            set {
                this.codigo_isoField = value;
                this.RaisePropertyChanged("codigo_iso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int moneda_id {
            get {
                return this.moneda_idField;
            }
            set {
                this.moneda_idField = value;
                this.RaisePropertyChanged("moneda_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moneda_idSpecified {
            get {
                return this.moneda_idFieldSpecified;
            }
            set {
                this.moneda_idFieldSpecified = value;
                this.RaisePropertyChanged("moneda_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string simbolo {
            get {
                return this.simboloField;
            }
            set {
                this.simboloField = value;
                this.RaisePropertyChanged("simbolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipos_cambio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public tiposDeCambioDTO[] tipos_cambio {
            get {
                return this.tipos_cambioField;
            }
            set {
                this.tipos_cambioField = value;
                this.RaisePropertyChanged("tipos_cambio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class usuarioPaisAccesoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool accesoField;
        
        private bool accesoFieldSpecified;
        
        private paisesDTO paisField;
        
        private usuariosDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool acceso {
            get {
                return this.accesoField;
            }
            set {
                this.accesoField = value;
                this.RaisePropertyChanged("acceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accesoSpecified {
            get {
                return this.accesoFieldSpecified;
            }
            set {
                this.accesoFieldSpecified = value;
                this.RaisePropertyChanged("accesoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public paisesDTO pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public usuariosDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class usuariosDTO : eliminableDTOBase {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string apellidosField;
        
        private string correo_electronicoField;
        
        private string nombreField;
        
        private string nombre_de_usuarioField;
        
        private string password_hashField;
        
        private bool superusuarioField;
        
        private bool superusuarioFieldSpecified;
        
        private int usuario_idField;
        
        private bool usuario_idFieldSpecified;
        
        private usuarioPaisAccesoDTO[] usuario_paisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo_electronico {
            get {
                return this.correo_electronicoField;
            }
            set {
                this.correo_electronicoField = value;
                this.RaisePropertyChanged("correo_electronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre_de_usuario {
            get {
                return this.nombre_de_usuarioField;
            }
            set {
                this.nombre_de_usuarioField = value;
                this.RaisePropertyChanged("nombre_de_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string password_hash {
            get {
                return this.password_hashField;
            }
            set {
                this.password_hashField = value;
                this.RaisePropertyChanged("password_hash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool superusuario {
            get {
                return this.superusuarioField;
            }
            set {
                this.superusuarioField = value;
                this.RaisePropertyChanged("superusuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool superusuarioSpecified {
            get {
                return this.superusuarioFieldSpecified;
            }
            set {
                this.superusuarioFieldSpecified = value;
                this.RaisePropertyChanged("superusuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int usuario_id {
            get {
                return this.usuario_idField;
            }
            set {
                this.usuario_idField = value;
                this.RaisePropertyChanged("usuario_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuario_idSpecified {
            get {
                return this.usuario_idFieldSpecified;
            }
            set {
                this.usuario_idFieldSpecified = value;
                this.RaisePropertyChanged("usuario_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("usuario_pais", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public usuarioPaisAccesoDTO[] usuario_pais {
            get {
                return this.usuario_paisField;
            }
            set {
                this.usuario_paisField = value;
                this.RaisePropertyChanged("usuario_pais");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(detallesFacturaDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(acreedoresDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(facturasDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuariosDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public abstract partial class eliminableDTOBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fecha_eliminacionField;
        
        private bool fecha_eliminacionFieldSpecified;
        
        private usuariosDTO usuario_eliminacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha_eliminacion {
            get {
                return this.fecha_eliminacionField;
            }
            set {
                this.fecha_eliminacionField = value;
                this.RaisePropertyChanged("fecha_eliminacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_eliminacionSpecified {
            get {
                return this.fecha_eliminacionFieldSpecified;
            }
            set {
                this.fecha_eliminacionFieldSpecified = value;
                this.RaisePropertyChanged("fecha_eliminacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public usuariosDTO usuario_eliminacion {
            get {
                return this.usuario_eliminacionField;
            }
            set {
                this.usuario_eliminacionField = value;
                this.RaisePropertyChanged("usuario_eliminacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softpacws.pucp.edu.pe/")]
    public partial class detallesFacturaDTO : eliminableDTOBase {
        
        private string descripcionField;
        
        private int detalle_factura_idField;
        
        private bool detalle_factura_idFieldSpecified;
        
        private facturasDTO facturaField;
        
        private decimal subtotalField;
        
        private bool subtotalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int detalle_factura_id {
            get {
                return this.detalle_factura_idField;
            }
            set {
                this.detalle_factura_idField = value;
                this.RaisePropertyChanged("detalle_factura_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool detalle_factura_idSpecified {
            get {
                return this.detalle_factura_idFieldSpecified;
            }
            set {
                this.detalle_factura_idFieldSpecified = value;
                this.RaisePropertyChanged("detalle_factura_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public facturasDTO factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
                this.RaisePropertyChanged("factura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtotalSpecified {
            get {
                return this.subtotalFieldSpecified;
            }
            set {
                this.subtotalFieldSpecified = value;
                this.RaisePropertyChanged("subtotalSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPendientesPorCriterios", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPendientesPorCriteriosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pais_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaLimite;
        
        public listarPendientesPorCriteriosRequest() {
        }
        
        public listarPendientesPorCriteriosRequest(int pais_id, System.DateTime fechaLimite) {
            this.pais_id = pais_id;
            this.fechaLimite = fechaLimite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPendientesPorCriteriosResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPendientesPorCriteriosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.FacturasWS.facturasDTO[] @return;
        
        public listarPendientesPorCriteriosResponse() {
        }
        
        public listarPendientesPorCriteriosResponse(SoftPacBusiness.FacturasWS.facturasDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarFacturas", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarFacturasRequest {
        
        public listarFacturasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarFacturasResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarFacturasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.FacturasWS.facturasDTO[] @return;
        
        public listarFacturasResponse() {
        }
        
        public listarFacturasResponse(SoftPacBusiness.FacturasWS.facturasDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarFactura", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.FacturasWS.facturasDTO factura;
        
        public modificarFacturaRequest() {
        }
        
        public modificarFacturaRequest(SoftPacBusiness.FacturasWS.facturasDTO factura) {
            this.factura = factura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarFacturaResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarFacturaResponse() {
        }
        
        public modificarFacturaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPendientes", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPendientesRequest {
        
        public listarPendientesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPendientesResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPendientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.FacturasWS.facturasDTO[] @return;
        
        public listarPendientesResponse() {
        }
        
        public listarPendientesResponse(SoftPacBusiness.FacturasWS.facturasDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerFactura", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int factura_id;
        
        public obtenerFacturaRequest() {
        }
        
        public obtenerFacturaRequest(int factura_id) {
            this.factura_id = factura_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerFacturaResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.FacturasWS.facturasDTO @return;
        
        public obtenerFacturaResponse() {
        }
        
        public obtenerFacturaResponse(SoftPacBusiness.FacturasWS.facturasDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarFactura", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.FacturasWS.facturasDTO factura;
        
        public insertarFacturaRequest() {
        }
        
        public insertarFacturaRequest(SoftPacBusiness.FacturasWS.facturasDTO factura) {
            this.factura = factura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarFacturaResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarFacturaResponse() {
        }
        
        public insertarFacturaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarFactura", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.FacturasWS.facturasDTO factura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.FacturasWS.usuariosDTO usuarioActual;
        
        public eliminarFacturaRequest() {
        }
        
        public eliminarFacturaRequest(SoftPacBusiness.FacturasWS.facturasDTO factura, SoftPacBusiness.FacturasWS.usuariosDTO usuarioActual) {
            this.factura = factura;
            this.usuarioActual = usuarioActual;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarFacturaResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarFacturaResponse() {
        }
        
        public eliminarFacturaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDetalleFactura", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarDetalleFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.FacturasWS.detallesFacturaDTO detalle;
        
        public insertarDetalleFacturaRequest() {
        }
        
        public insertarDetalleFacturaRequest(SoftPacBusiness.FacturasWS.detallesFacturaDTO detalle) {
            this.detalle = detalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDetalleFacturaResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarDetalleFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarDetalleFacturaResponse() {
        }
        
        public insertarDetalleFacturaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarDetalleFactura", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarDetalleFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.FacturasWS.detallesFacturaDTO detalle;
        
        public modificarDetalleFacturaRequest() {
        }
        
        public modificarDetalleFacturaRequest(SoftPacBusiness.FacturasWS.detallesFacturaDTO detalle) {
            this.detalle = detalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarDetalleFacturaResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarDetalleFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarDetalleFacturaResponse() {
        }
        
        public modificarDetalleFacturaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDetalleFactura", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarDetalleFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.FacturasWS.detallesFacturaDTO detalle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPacBusiness.FacturasWS.usuariosDTO usuarioActual;
        
        public eliminarDetalleFacturaRequest() {
        }
        
        public eliminarDetalleFacturaRequest(SoftPacBusiness.FacturasWS.detallesFacturaDTO detalle, SoftPacBusiness.FacturasWS.usuariosDTO usuarioActual) {
            this.detalle = detalle;
            this.usuarioActual = usuarioActual;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDetalleFacturaResponse", WrapperNamespace="http://softpacws.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarDetalleFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softpacws.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarDetalleFacturaResponse() {
        }
        
        public eliminarDetalleFacturaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FacturasWSChannel : SoftPacBusiness.FacturasWS.FacturasWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacturasWSClient : System.ServiceModel.ClientBase<SoftPacBusiness.FacturasWS.FacturasWS>, SoftPacBusiness.FacturasWS.FacturasWS {
        
        public FacturasWSClient() {
        }
        
        public FacturasWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacturasWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturasWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturasWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosResponse SoftPacBusiness.FacturasWS.FacturasWS.listarPendientesPorCriterios(SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosRequest request) {
            return base.Channel.listarPendientesPorCriterios(request);
        }
        
        public SoftPacBusiness.FacturasWS.facturasDTO[] listarPendientesPorCriterios(int pais_id, System.DateTime fechaLimite) {
            SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosRequest inValue = new SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosRequest();
            inValue.pais_id = pais_id;
            inValue.fechaLimite = fechaLimite;
            SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosResponse retVal = ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).listarPendientesPorCriterios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosResponse> SoftPacBusiness.FacturasWS.FacturasWS.listarPendientesPorCriteriosAsync(SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosRequest request) {
            return base.Channel.listarPendientesPorCriteriosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosResponse> listarPendientesPorCriteriosAsync(int pais_id, System.DateTime fechaLimite) {
            SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosRequest inValue = new SoftPacBusiness.FacturasWS.listarPendientesPorCriteriosRequest();
            inValue.pais_id = pais_id;
            inValue.fechaLimite = fechaLimite;
            return ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).listarPendientesPorCriteriosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.FacturasWS.listarFacturasResponse SoftPacBusiness.FacturasWS.FacturasWS.listarFacturas(SoftPacBusiness.FacturasWS.listarFacturasRequest request) {
            return base.Channel.listarFacturas(request);
        }
        
        public SoftPacBusiness.FacturasWS.facturasDTO[] listarFacturas() {
            SoftPacBusiness.FacturasWS.listarFacturasRequest inValue = new SoftPacBusiness.FacturasWS.listarFacturasRequest();
            SoftPacBusiness.FacturasWS.listarFacturasResponse retVal = ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).listarFacturas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.listarFacturasResponse> SoftPacBusiness.FacturasWS.FacturasWS.listarFacturasAsync(SoftPacBusiness.FacturasWS.listarFacturasRequest request) {
            return base.Channel.listarFacturasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.listarFacturasResponse> listarFacturasAsync() {
            SoftPacBusiness.FacturasWS.listarFacturasRequest inValue = new SoftPacBusiness.FacturasWS.listarFacturasRequest();
            return ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).listarFacturasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.FacturasWS.modificarFacturaResponse SoftPacBusiness.FacturasWS.FacturasWS.modificarFactura(SoftPacBusiness.FacturasWS.modificarFacturaRequest request) {
            return base.Channel.modificarFactura(request);
        }
        
        public int modificarFactura(SoftPacBusiness.FacturasWS.facturasDTO factura) {
            SoftPacBusiness.FacturasWS.modificarFacturaRequest inValue = new SoftPacBusiness.FacturasWS.modificarFacturaRequest();
            inValue.factura = factura;
            SoftPacBusiness.FacturasWS.modificarFacturaResponse retVal = ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).modificarFactura(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.modificarFacturaResponse> SoftPacBusiness.FacturasWS.FacturasWS.modificarFacturaAsync(SoftPacBusiness.FacturasWS.modificarFacturaRequest request) {
            return base.Channel.modificarFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.modificarFacturaResponse> modificarFacturaAsync(SoftPacBusiness.FacturasWS.facturasDTO factura) {
            SoftPacBusiness.FacturasWS.modificarFacturaRequest inValue = new SoftPacBusiness.FacturasWS.modificarFacturaRequest();
            inValue.factura = factura;
            return ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).modificarFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.FacturasWS.listarPendientesResponse SoftPacBusiness.FacturasWS.FacturasWS.listarPendientes(SoftPacBusiness.FacturasWS.listarPendientesRequest request) {
            return base.Channel.listarPendientes(request);
        }
        
        public SoftPacBusiness.FacturasWS.facturasDTO[] listarPendientes() {
            SoftPacBusiness.FacturasWS.listarPendientesRequest inValue = new SoftPacBusiness.FacturasWS.listarPendientesRequest();
            SoftPacBusiness.FacturasWS.listarPendientesResponse retVal = ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).listarPendientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.listarPendientesResponse> SoftPacBusiness.FacturasWS.FacturasWS.listarPendientesAsync(SoftPacBusiness.FacturasWS.listarPendientesRequest request) {
            return base.Channel.listarPendientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.listarPendientesResponse> listarPendientesAsync() {
            SoftPacBusiness.FacturasWS.listarPendientesRequest inValue = new SoftPacBusiness.FacturasWS.listarPendientesRequest();
            return ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).listarPendientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.FacturasWS.obtenerFacturaResponse SoftPacBusiness.FacturasWS.FacturasWS.obtenerFactura(SoftPacBusiness.FacturasWS.obtenerFacturaRequest request) {
            return base.Channel.obtenerFactura(request);
        }
        
        public SoftPacBusiness.FacturasWS.facturasDTO obtenerFactura(int factura_id) {
            SoftPacBusiness.FacturasWS.obtenerFacturaRequest inValue = new SoftPacBusiness.FacturasWS.obtenerFacturaRequest();
            inValue.factura_id = factura_id;
            SoftPacBusiness.FacturasWS.obtenerFacturaResponse retVal = ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).obtenerFactura(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.obtenerFacturaResponse> SoftPacBusiness.FacturasWS.FacturasWS.obtenerFacturaAsync(SoftPacBusiness.FacturasWS.obtenerFacturaRequest request) {
            return base.Channel.obtenerFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.obtenerFacturaResponse> obtenerFacturaAsync(int factura_id) {
            SoftPacBusiness.FacturasWS.obtenerFacturaRequest inValue = new SoftPacBusiness.FacturasWS.obtenerFacturaRequest();
            inValue.factura_id = factura_id;
            return ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).obtenerFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.FacturasWS.insertarFacturaResponse SoftPacBusiness.FacturasWS.FacturasWS.insertarFactura(SoftPacBusiness.FacturasWS.insertarFacturaRequest request) {
            return base.Channel.insertarFactura(request);
        }
        
        public int insertarFactura(SoftPacBusiness.FacturasWS.facturasDTO factura) {
            SoftPacBusiness.FacturasWS.insertarFacturaRequest inValue = new SoftPacBusiness.FacturasWS.insertarFacturaRequest();
            inValue.factura = factura;
            SoftPacBusiness.FacturasWS.insertarFacturaResponse retVal = ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).insertarFactura(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.insertarFacturaResponse> SoftPacBusiness.FacturasWS.FacturasWS.insertarFacturaAsync(SoftPacBusiness.FacturasWS.insertarFacturaRequest request) {
            return base.Channel.insertarFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.insertarFacturaResponse> insertarFacturaAsync(SoftPacBusiness.FacturasWS.facturasDTO factura) {
            SoftPacBusiness.FacturasWS.insertarFacturaRequest inValue = new SoftPacBusiness.FacturasWS.insertarFacturaRequest();
            inValue.factura = factura;
            return ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).insertarFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.FacturasWS.eliminarFacturaResponse SoftPacBusiness.FacturasWS.FacturasWS.eliminarFactura(SoftPacBusiness.FacturasWS.eliminarFacturaRequest request) {
            return base.Channel.eliminarFactura(request);
        }
        
        public int eliminarFactura(SoftPacBusiness.FacturasWS.facturasDTO factura, SoftPacBusiness.FacturasWS.usuariosDTO usuarioActual) {
            SoftPacBusiness.FacturasWS.eliminarFacturaRequest inValue = new SoftPacBusiness.FacturasWS.eliminarFacturaRequest();
            inValue.factura = factura;
            inValue.usuarioActual = usuarioActual;
            SoftPacBusiness.FacturasWS.eliminarFacturaResponse retVal = ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).eliminarFactura(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.eliminarFacturaResponse> SoftPacBusiness.FacturasWS.FacturasWS.eliminarFacturaAsync(SoftPacBusiness.FacturasWS.eliminarFacturaRequest request) {
            return base.Channel.eliminarFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.eliminarFacturaResponse> eliminarFacturaAsync(SoftPacBusiness.FacturasWS.facturasDTO factura, SoftPacBusiness.FacturasWS.usuariosDTO usuarioActual) {
            SoftPacBusiness.FacturasWS.eliminarFacturaRequest inValue = new SoftPacBusiness.FacturasWS.eliminarFacturaRequest();
            inValue.factura = factura;
            inValue.usuarioActual = usuarioActual;
            return ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).eliminarFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.FacturasWS.insertarDetalleFacturaResponse SoftPacBusiness.FacturasWS.FacturasWS.insertarDetalleFactura(SoftPacBusiness.FacturasWS.insertarDetalleFacturaRequest request) {
            return base.Channel.insertarDetalleFactura(request);
        }
        
        public int insertarDetalleFactura(SoftPacBusiness.FacturasWS.detallesFacturaDTO detalle) {
            SoftPacBusiness.FacturasWS.insertarDetalleFacturaRequest inValue = new SoftPacBusiness.FacturasWS.insertarDetalleFacturaRequest();
            inValue.detalle = detalle;
            SoftPacBusiness.FacturasWS.insertarDetalleFacturaResponse retVal = ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).insertarDetalleFactura(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.insertarDetalleFacturaResponse> SoftPacBusiness.FacturasWS.FacturasWS.insertarDetalleFacturaAsync(SoftPacBusiness.FacturasWS.insertarDetalleFacturaRequest request) {
            return base.Channel.insertarDetalleFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.insertarDetalleFacturaResponse> insertarDetalleFacturaAsync(SoftPacBusiness.FacturasWS.detallesFacturaDTO detalle) {
            SoftPacBusiness.FacturasWS.insertarDetalleFacturaRequest inValue = new SoftPacBusiness.FacturasWS.insertarDetalleFacturaRequest();
            inValue.detalle = detalle;
            return ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).insertarDetalleFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.FacturasWS.modificarDetalleFacturaResponse SoftPacBusiness.FacturasWS.FacturasWS.modificarDetalleFactura(SoftPacBusiness.FacturasWS.modificarDetalleFacturaRequest request) {
            return base.Channel.modificarDetalleFactura(request);
        }
        
        public int modificarDetalleFactura(SoftPacBusiness.FacturasWS.detallesFacturaDTO detalle) {
            SoftPacBusiness.FacturasWS.modificarDetalleFacturaRequest inValue = new SoftPacBusiness.FacturasWS.modificarDetalleFacturaRequest();
            inValue.detalle = detalle;
            SoftPacBusiness.FacturasWS.modificarDetalleFacturaResponse retVal = ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).modificarDetalleFactura(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.modificarDetalleFacturaResponse> SoftPacBusiness.FacturasWS.FacturasWS.modificarDetalleFacturaAsync(SoftPacBusiness.FacturasWS.modificarDetalleFacturaRequest request) {
            return base.Channel.modificarDetalleFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.modificarDetalleFacturaResponse> modificarDetalleFacturaAsync(SoftPacBusiness.FacturasWS.detallesFacturaDTO detalle) {
            SoftPacBusiness.FacturasWS.modificarDetalleFacturaRequest inValue = new SoftPacBusiness.FacturasWS.modificarDetalleFacturaRequest();
            inValue.detalle = detalle;
            return ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).modificarDetalleFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPacBusiness.FacturasWS.eliminarDetalleFacturaResponse SoftPacBusiness.FacturasWS.FacturasWS.eliminarDetalleFactura(SoftPacBusiness.FacturasWS.eliminarDetalleFacturaRequest request) {
            return base.Channel.eliminarDetalleFactura(request);
        }
        
        public int eliminarDetalleFactura(SoftPacBusiness.FacturasWS.detallesFacturaDTO detalle, SoftPacBusiness.FacturasWS.usuariosDTO usuarioActual) {
            SoftPacBusiness.FacturasWS.eliminarDetalleFacturaRequest inValue = new SoftPacBusiness.FacturasWS.eliminarDetalleFacturaRequest();
            inValue.detalle = detalle;
            inValue.usuarioActual = usuarioActual;
            SoftPacBusiness.FacturasWS.eliminarDetalleFacturaResponse retVal = ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).eliminarDetalleFactura(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.eliminarDetalleFacturaResponse> SoftPacBusiness.FacturasWS.FacturasWS.eliminarDetalleFacturaAsync(SoftPacBusiness.FacturasWS.eliminarDetalleFacturaRequest request) {
            return base.Channel.eliminarDetalleFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPacBusiness.FacturasWS.eliminarDetalleFacturaResponse> eliminarDetalleFacturaAsync(SoftPacBusiness.FacturasWS.detallesFacturaDTO detalle, SoftPacBusiness.FacturasWS.usuariosDTO usuarioActual) {
            SoftPacBusiness.FacturasWS.eliminarDetalleFacturaRequest inValue = new SoftPacBusiness.FacturasWS.eliminarDetalleFacturaRequest();
            inValue.detalle = detalle;
            inValue.usuarioActual = usuarioActual;
            return ((SoftPacBusiness.FacturasWS.FacturasWS)(this)).eliminarDetalleFacturaAsync(inValue);
        }
    }
}
